scaffold-eth/scaffold-eth-2

README.md, package.json, packages/hardhat/hardhat.config.ts, packages/hardhat/package.json, packages/hardhat/scripts/generateAccount.ts, packages/hardhat/scripts/listAccount.ts, yarn.lock
Took a different approach than SE1.
`yarn generate` will create/update the .env file with a private key.
For `yarn account` I'm using a more up to date (support with ES6 included :)) QR lib than SE1.
Also using hardhat scripts (instead of tasks)
P.S. We could also generate a mnemonic instead of a private key... but went for the private key, since hardhat.config was already using a private key.
=> Account helper functions (generate / account)

packages/nextjs/components/Footer.tsx, packages/nextjs/components/SwitchTheme.tsx
Setted up a basic toggle button : 
https://user-images.githubusercontent.com/80153681/210176539-4d93f3e8-a611-4f96-bbc4-ad47d86e70a4.mov
Utilized [`useDarkMode` ](https://usehooks-ts.com/react-hook/use-dark-mode) hook provided by usehooks-ts library. 
- I felt that theme-change could have been more useful if we have had more than two themes because for only light and dark theme we have already have `useDarkMode` which takes care off cases from persisting it in localstorage to grabbing the default OS theme and setting it based on that. 
- but if we plan to have more themes then theme-change seems best for this purpose. 
Fixes #79
=> theme toggle button

packages/nextjs/components/scaffold-eth/Balance.tsx, packages/nextjs/components/scaffold-eth/Faucet.tsx, packages/nextjs/hooks/scaffold-eth/useAccountBalance.ts, packages/nextjs/hooks/scaffold-eth/useWalletBalance.ts, packages/nextjs/tailwind.config.js
daisyui doesn't support complex tooltips, like bottom-left, only centered bottom or centered left. So I placed the tooltip to the left (only when the balance is 0)
bottom variant is bad:
Possible solutions if you want the bottom tooltip:
- move the faucet button to the left
- use something like `react-popper` https://popper.js.org/react-popper/v2/
=> Grab funds tooltip

packages/nextjs/components/scaffold-eth/Address.tsx, packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx, packages/nextjs/pages/debug.tsx, packages/nextjs/tailwind.config.js, packages/nextjs/utils/scaffold-eth/networks.ts, packages/nextjs/utils/scaffold-eth/useNetworkColor.ts
changed the description text color to default, because we don't have a gray color variable for themes. For example, we can use `neutral` color, but not sure. Also, I don't like the way to calculate the color for networks, but for now it at least looks better.
before:
after:
=> update dark theme

packages/nextjs/components/scaffold-eth/Contract/utilsContract.tsx
In `utilsContract.tsx` we had:
```js
// ToDo. Handle when this doesn't exist?
import ContractData from "~~/generated/hardhat_contracts.json";
```
If people follow the command order specified in the README (chain, deploy, start) this error will never happen. But I feel that we should handle this error, in case the `hardhat_contract.json` is not there.
I tried a few approaches, and this one feels like the most simple one. 
It gives a warning in the console, but not in the UI. UI only gives an error if the file exists and you delete (which seems an edge use case :D).
Can you double check @technophile-04 ?
Happy to consider another approach.
=> Handle error when hardhat_contracts.json doesnt exist

packages/nextjs/.env.development, packages/nextjs/.env.production
It seems we are another chain name like `homestead` instead of `mainnet` (might be due to wagmi latest update) which causes the below problem : 
https://user-images.githubusercontent.com/80153681/216852150-a30f6a43-d536-4c96-b683-061de16d6e01.mov
Updated the lookup comment chain name in `env` and also added a link to supported chains from wagmi docs
=> Fix network names in env's and add reference to supported chains

packages/nextjs/components/scaffold-eth/AddressInput.tsx, packages/nextjs/components/scaffold-eth/Contract/InputUI.tsx
When using <AddressInput/> outside the Debug page, you were getting a "ghost" input (no borders, invisible when empty)
Before:
After:
=> Fix ghost input when using Address Input

packages/nextjs/components/scaffold-eth/AddressInput.tsx
In dark mode, the address input has a different background color than the regular input. This small fix aligns both to use the expected dark background.
=> fix(input): dark mode address input background should be aligned with regular input

packages/hardhat/contracts/YourContract.sol, packages/nextjs/components/scaffold-eth/Contract/InputUI.tsx, packages/nextjs/components/scaffold-eth/Contract/ReadOnlyFunctionForm.tsx, packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx, packages/nextjs/components/scaffold-eth/Contract/utilsContract.tsx
Inspiration was taken from here https://github.com/scaffold-eth/scaffold-eth/blob/e4afffc7e3d6c2bb575240b4de830703e8925548/packages/react-app/src/components/Contract/FunctionForm.jsx#L192 
https://user-images.githubusercontent.com/80153681/218545117-82ca6887-6ff6-4e62-bf1d-86d66dc8e2e1.mov
currently, if you look at `getParsedContractFunctionArgs` we are there ignoring the error and leaving on wagmi to handle the error. Instead what we can use is `recklesslySetUnpreparedArgs` and check before sending the transaction. Checkout its usage  here -> https://wagmi.sh/react/hooks/useContractWrite#override-config, since its discouraged by wagmi used the current approach but happy to take either approach 🙌
Also, feel free to suggest a change in name of the newly created util function
cc @carletex …
=> support arrays input for Contract component

packages/hardhat/contracts/YourContract.sol, packages/nextjs/components/scaffold-eth/Contract/ReadOnlyFunctionForm.tsx
It seems if the contract read function returns `false` then its not show in the UI 
https://user-images.githubusercontent.com/80153681/219032901-2152254f-6e49-413c-9b51-3c0d475f437e.mov
https://user-images.githubusercontent.com/80153681/219033862-fa27f9d6-edce-42b1-9ab1-0163a94e74c5.mov
used looseEqual to check only for null and undefined, checkout -> https://stackoverflow.com/a/15992131
cc @carletex @rin-st, would be happy to refactor if I missed some cases 🙌
=> fix: show literal false value returned by contract

packages/nextjs/components/Footer.tsx
When you configure `env` network other than `hardhat` we get the following error  on the first render: 
Since `getFaucetAddress` is used in `useEffect` and is called on render irrespective of chain configured in `env` https://github.com/scaffold-eth/se-2/blob/2a61bc87ac80f1e2de9dd6cad0cc10eebf2703e6/packages/nextjs/components/scaffold-eth/Faucet.tsx#L48
Added a guard at `Footer.jsx` level, since this seems the most minimal and clean
Instead of adding guard at `Footer.jsx` level, we can have it before calling the function https://github.com/scaffold-eth/se-2/blob/2a61bc87ac80f1e2de9dd6cad0cc10eebf2703e6/packages/nextjs/components/scaffold-eth/Faucet.tsx#L48
=> Error toast of faucet on deployement networks

packages/nextjs/components/scaffold-eth/Contract/utilsComponents.tsx
The asterisk button to multiply the value by 10^18 was very narrow and not always easy to click. This fix improves accessibility by increasing its "hitbox".
=> fix(multiply string): make the button hitbox larger to improve UX

packages/nextjs/components/scaffold-eth/Balance.tsx, packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx
Fixes balance view, it's broken for some resolutions, and now it's clear what that value means. Also changed "Network:" text color.
before:
after:
=> fix: balance view

packages/nextjs/components/scaffold-eth/EtherInput.tsx
It was confusing
Before:
After:
=> Remove USD / ETH from EtherInput

packages/nextjs/components/scaffold-eth/Address.tsx
- Show EnsAvatar on the Address component (if any).
- Rounded blockie (+ bigger size) to match UI vibe
- Remove extra stuff (font-size / minimized). It was inherited from SE1, we are not using rn... and it had some missing stuff (like adjusting the text fontsize). We'll be standardizing components soon (maybe "classNames" as the Balance component).
**Before**
**After**
=> Address component: EnsAvatar + cleanup

packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx, packages/nextjs/utils/scaffold-eth/networks.ts
Because of the naming of mainnet in wagmi/rainbowkit (homestead), when `NEXT_PUBLIC_NETWORK` was "mainnet" it wasn't working. Using `homestead` on `NEXT_PUBLIC_NETWORK` wasn't working either (because our logic).
---
This is kind of time sensitive so I created this hotfix. Merging it and hoping not to break anything :angel: 
We need to think how to handle networks better and define a source of truth for networks (maybe our `networks.ts`?). 
Also refactor things like this (and use our `getTargetNetwork`):
This is also related to #168
Let's review this next week @technophile-04 @rin-st
=> HOTFIX: Mainnet working when selected as target network

packages/nextjs/components/Header.tsx, packages/nextjs/pages/_app.tsx
For improved UX (especially on mobile), I think the header should be sticky in order to always have easy access to navigation and address functionalities.
=> feat(nav): make top nav sticky for easier access on mobile

packages/nextjs/utils/scaffold-eth/networks.ts
There are very less chances that dev might delete `NEXT_PUBLIC_NETWORK` from `env` but if he does so then he won't get any error in the console and network will be set to `hardhat` without letting him know 
Originally discussed here -> https://github.com/scaffold-eth/se-2/pull/182/files#r1111042625
=> handle edge-case for getTargetNetwork

packages/nextjs/components/ExampleUi/ContractData.tsx, packages/nextjs/hooks/scaffold-eth/useScaffoldContractRead.ts
Fixes #189 
I propose keeping it rather simple and clean in a first step. The user should know what the return type is (since he'll use it). He can choose to use the return value as `any`, or he can provide the type if he wants better type-safety.
=> fix(types): allow generically set return type for contract read hooks

package.json, packages/hardhat/hardhat.config.ts, packages/hardhat/package.json
As in SE1, we want to be able to run our local hardhat node with mainnet forking.
Don't feel super happy about putting the API Key on package.json, even if we already exposed it in `hardhat.config.js`. It's a default alchemy key we have for SE1.
It's always about finding the balance between: good practices & easy-to-use/no-config
Thoughts? Any other approaches?
---
cc @technophile-04 @rin-st @sverps
=> "yarn fork" command for mainnet forking

packages/nextjs/.env.development, packages/nextjs/.env.production, packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx, packages/nextjs/hooks/scaffold-eth/useNetworkColor.ts, packages/nextjs/services/web3/wagmiConnectors.tsx, packages/nextjs/utils/scaffold-eth/networks.ts
Fixes #168 
- We had a mix between our own defined networks (in `networks.ts`) and wagmi networks. In this PR, we are using wagmi networks as the source of truth and using our `NETWORKS` (now `NETWORKS_EXTRA_DATA`) as a way to adding extra metadata to some networks (right now it's only the color, but in the future, it could be: displayName, BlockExplorer, etc)
- Wagmi/Rainbowkit available networks are now only the target app network (`NEXT_PUBLIC_NETWORK`) and mainnet (we need it for ENS resolution, Get ETH price, etc)
- Removed the network switcher (as discussed in #168), but we now show the target network below the balance (thanks Andrea for this!)
Would love to hear your thoughts on this @rin-st @technophile-04 and make sure that I'm not missing anything.
=> Supported networks

packages/hardhat/package.json, packages/nextjs/package.json, yarn.lock
- Updated wagmi, no breaking changes from 0.10.x -> 0.11.x [migration guide](https://wagmi.sh/react/migration-guide#011x-breaking-changes)
- Update typescript from @4.7.x -> 4.9.x was suggested in [migration guide](https://wagmi.sh/react/migration-guide#011x-breaking-changes) also no likely breaking for typescript too -> [changes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#correctness-fixes-and-breaking-changes)
- Updated rainbowkit to 0.11.0 ...Its not mentioned in the migration guide but mostly mentioned no breaking changes checkout https://github.com/rainbow-me/rainbowkit/pull/1000 also from 0.8x -> 0.10x they have been just updating version of wagmi their migration guide -> https://www.rainbowkit.com/docs/migration-guide
Here is live deployed app -> …
=> Upgrade wagmi rainbowkit to fix modal bug

packages/nextjs/hooks/scaffold-eth/useTransactor.tsx
I think we inherited this from SE-1. We had issues yesterday while using the transactor to send Goerli tx (we had to manually speed them up from metamask)
1. We don't want to send legacy tx (we want maxPriorityFeePerGas / maxFeePerGas)
2. ethers populate the values when calling sendTransaction on populateTx (asking the network) 
The only use case might be using a weird network that doesn't provide gas fees values. We can leave it for the future (maybe configuring that value on `NETWORKS_EXTRA_DATA` and using it on the transactor`)
=> Remove hardcoded gas

packages/nextjs/hooks/scaffold-eth/useScaffoldContractRead.ts
This is kind of a hotfix (until #147 #207 or #200 is merged). That's why I went with `any[]` :D 
On yesterday's hacking session, we realized we couldn't read contract data that require params.
e.g.
```
const { data } = useScaffoldContractRead("YourContract", "userGreetingCounter", [
"0xWHATEVER_ADDRESS",
]);
```
Technically you could pass it on `readConfig`, but I think this is more clear. Should we also add `writeConfig` on `scaffoldContractWrite`? (we can leave it for other PR)
=> Argument "args" on scaffoldContractRead

packages/nextjs/.env.development, packages/nextjs/.env.production, packages/nextjs/hooks/scaffold-eth/useScaffoldContractRead.ts
Noticed it while hacking se-2 : 
1. You are not able to pass other types as generic expect `BigNumber | boolean | string`, I think we should not restrict just to `BigNumber | boolean | string` and allow developers to pass in what they want, since sometime your function may return `struct` or other types. 
2. Added `polygonMumbai` to `.env's`, lots of people use `mumbai` for hacking and it would great if we add reference in comments itself so that developers don't have to go to wagmi's doc (we can completely ignore this though)
=> remove restriction for useScaffoldContractRead generic

packages/nextjs/components/scaffold-eth/Contract/TxReceipt.tsx
Lost the tx receipt arrow on 2fbebaceace89d326b9b24720ff349d8446de687
Fix:
=> Fix collapse arrow on tx receipt

packages/nextjs/components/scaffold-eth/Contract/utilsContract.tsx
In some cases, we can have function overloads in solidity contracts, for example when using
`contract Abc is ERC721Enumerable`
=> fix: write and read methods keys

packages/nextjs/.env.development, packages/nextjs/.env.production, packages/nextjs/components/Footer.tsx, packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx, packages/nextjs/components/scaffold-eth/Contract/DisplayVariable.tsx, packages/nextjs/components/scaffold-eth/Contract/ReadOnlyFunctionForm.tsx, packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx, packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx, packages/nextjs/hooks/scaffold-eth/useAccountBalance.ts, packages/nextjs/hooks/scaffold-eth/useAutoConnect.ts, packages/nextjs/hooks/scaffold-eth/useDeployedContractInfo.ts, packages/nextjs/hooks/scaffold-eth/useDeployedContractNames.ts, packages/nextjs/hooks/scaffold-eth/useEthPrice.ts, packages/nextjs/hooks/scaffold-eth/useNetworkColor.ts, packages/nextjs/hooks/scaffold-eth/useScaffoldContractRead.ts, packages/nextjs/hooks/scaffold-eth/useScaffoldContractWrite.ts, packages/nextjs/hooks/scaffold-eth/useScaffoldEventSubscriber.ts, packages/nextjs/scaffold.config.ts, packages/nextjs/services/web3/wagmi-burner/burnerWalletConfig.ts, packages/nextjs/services/web3/wagmiConnectors.tsx, packages/nextjs/tsconfig.json, packages/nextjs/utils/scaffold-eth/networks.ts
Added a  `scaffold.config.ts` in frontend instead for now as discussed in https://github.com/scaffold-eth/se-2/pull/231. 
Updated `network.ts` now it uses block explores links from `targetNetowork` and now you get transaction link for different blockexplores previously it used only show for etherscan and dai.... its the same as  https://github.com/scaffold-eth/se-2/pull/231#discussion_r1132625398
would love to make it more robust and inline in different PR 🙌
1. `targetNetwork` from `scaffold.config.ts` is single source of truth now for frontend
2. Removed .env.* and added them inside `scaffold.config.ts`
=> Use .config for frontend instaed of env's

README.md, packages/hardhat/package.json, packages/nextjs/components/Footer.tsx, packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx, packages/nextjs/components/scaffold-eth/Contract/DisplayVariable.tsx, packages/nextjs/components/scaffold-eth/Contract/ReadOnlyFunctionForm.tsx, packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx, packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx, packages/nextjs/hooks/scaffold-eth/useAccountBalance.ts, packages/nextjs/hooks/scaffold-eth/useAutoConnect.ts, packages/nextjs/hooks/scaffold-eth/useDeployedContractInfo.ts, packages/nextjs/hooks/scaffold-eth/useDeployedContractNames.ts, packages/nextjs/hooks/scaffold-eth/useNetworkColor.ts, packages/nextjs/hooks/scaffold-eth/useScaffoldContractRead.ts, packages/nextjs/hooks/scaffold-eth/useScaffoldContractWrite.ts, packages/nextjs/hooks/scaffold-eth/useScaffoldEventSubscriber.ts, packages/nextjs/package.json, packages/nextjs/scaffold.config.ts, packages/nextjs/services/web3/wagmi-burner/burnerWalletConfig.ts, packages/nextjs/services/web3/wagmiConnectors.tsx, packages/nextjs/utils/scaffold-eth/networks.ts, yarn.lock
This is a small patch for #246, it seems that in that PR when we try to access `targetNetwork` types widening was happens 
Now : 
Had to upgrade prettier since support typescript `satisfies` was added in 2.8 checkout -> https://prettier.io/blog/2022/11/23/2.8.0.html
=> Fix: Infer types literal for scaffold.config

README.md
Renamed `hardhat.config.js` -> `hardhat.config.ts` in README.md
=> Fix typo in README hardhat.config.js to .ts

packages/nextjs/components/scaffold-eth/Faucet.tsx, packages/nextjs/hooks/scaffold-eth/useAutoConnect.ts, packages/nextjs/scripts/generateEmptyContractFile.mjs, packages/nextjs/utils/scaffold-eth/contract.ts
@carletex I cleaned it up a little and the empty contracts is now `null`, that way we no longer need to check `Object.keys().length`, which is a bit cleaner.
=> refactor: small improvement for empty contracts

packages/nextjs/components/scaffold-eth/Address.tsx, packages/nextjs/utils/scaffold-eth/networks.ts
Fixes #265 
- Liked the approach mentioned by Carlos in https://github.com/scaffold-eth/se-2/issues/265#issue-1645509779 so used it. 
- Moved this function to `network.ts` below `getBlockExplorerTxLink` as `getBlockExplorerAddressLink`, don't know if it was worth it.....Should we move it back to the Address component?  Its seems little consistent in `network.ts`
Also was wondering if should we handle https://github.com/scaffold-eth/se-2/pull/231#discussion_r1132625398 in this PR itself?
=> use targetNetwork blockExplorer link for AddressComponent

packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx
As commented here: [issue 300](https://github.com/scaffold-eth/se-2/issues/300#issuecomment-1512725914) to improve the user experience and simplify the network switching (which had networks that may confuse the user) I've replaced the existing modal with a dropdown menu that appears when the user is on the wrong network. 
The dropdown menu only includes the target network switch option and the disconnect option. Here is a video of the new behaviour: [PR se-2 issue-300 - Watch Video](https://www.loom.com/share/82e23277107548479d26afbd3c019eea)
=> Change Switch Network modal for a dropdown with only the target network

CONTRIBUTING.md, README.md, packages/hardhat/test/YouContract.ts, packages/nextjs/pages/example-ui.tsx, packages/nextjs/pages/index.tsx, packages/nextjs/services/web3/wagmiConnectors.tsx
Updated the nomenclature in line with the latest naming
=> update nomenclature inline with latest naming

README.md, packages/nextjs/components/scaffold-eth/Faucet.tsx, packages/nextjs/hooks/scaffold-eth/useAutoConnect.ts
It seems that due to the below check autoConnect does not work if you use SE-2 that doesn't use deployed contract : 
https://github.com/scaffold-eth/se-2/blob/ce83d166df62083a3aac86a6dda1802737a02fa8/packages/nextjs/hooks/scaffold-eth/useAutoConnect.ts#L68
Selected Mainnet as `targetNetwork`
https://user-images.githubusercontent.com/80153681/230662110-f12dac45-13b0-444b-bcb2-0c552a10504a.mov
--- 
Fixed by removing the `if(contract)` from both `useAutoConnect` & `Faucet`, it seems that check was added due console getting bloated with errors and warning but I think it was fixed in other commits 
checkout OG comment : https://github.com/scaffold-eth/se-2/pull/255/files/43f82e58bab2f624b60f520e68cfff749fe541e7#r1147414048
https://user-images.githubusercontent.com/80153681/230661918-c66089cb-5b …
=> Fix autoConnect when contract not deployed

packages/nextjs/components/Footer.tsx, packages/nextjs/components/scaffold-eth/Input/EtherInput.tsx, packages/nextjs/hooks/scaffold-eth/useAccountBalance.ts, packages/nextjs/pages/_app.tsx, packages/nextjs/services/store/store.ts
Whenever I'm hacking with @austintgriffith and we need to use `useAppStore`, we find it a bit confusing. I think this is especially true for iPhone users :D Where AppStore means something else.
I suggest changing it to something less confusing like `useAppState`. I like it because it resembles `useState`, but for the whole app. Another option we discussed was `useGlobalState`.
Thoughts?
=> useAppStore => useGlobalState

packages/nextjs/components/example-ui/ContractData.tsx, packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
Hey guys,
I've noticed that the Example UI page keeps re-rendering (see the console logs), because the filters object is used as a dependency of the useEffect hook.
Memoizing the object solved the issue for me.
Cheers,
Tamas
https://github.com/scaffold-eth/scaffold-eth-2/assets/1397179/acacd893-a745-4c8c-aaaa-aa335fa01f82
monyo.eth
=> Memoize filters to avoid infinite rendering

README.md, packages/hardhat/hardhat.config.ts
Hey guys,
This PR is about the Solidity compiler's Optimizer.
It is enabled by default in the original scaffold-eth [repo](https://github.com/scaffold-eth/scaffold-eth/blob/fc2ae9213be121e9e813d0c6fcb02cbc21d3593f/packages/hardhat/hardhat.config.js#L283). 
I wasn't sure if I should just enable it for scaffold-eth-2 as well, or not. I decided to only add it as an option and update the readme, to let people know about this, before they deploy to a Live network.
Let me know what do you think.
Best,
Tamas
=> Solidity Optimizer options

packages/nextjs/components/scaffold-eth/Balance.tsx
When displaying Balance component with larger font-size, the ETH / $ symbol remains `text-xs`
Use `text-[...em]` instead of `text-xs`. This sets an `em` value instead of a `rem` value, to ensure the symbol size is modified relative to the local font-size rather than that of the document root.
=> fix(Balance): font-size of symbol should be relative to current font-size, not document root

packages/nextjs/utils/scaffold-eth/contract.ts
Fixes #374
Make a very long contract.ts file by just copy-pasting the `greeting` view function (no need to actually deploy or make a valid Abi). At a certain length, TypeScript starts returning errors when running `yarn next:check-types`.
Contract abi's well over 2000 lines long can hit the typescript type instantiation limit (see [context of this limit](https://github.com/microsoft/TypeScript/issues/34933)). A workaround is described [here](https://stackoverflow.com/a/74292294/5000057).
Applying it does seem to resolve the issue.
=> fix(contract.ts): very long abi's now no longer go over type instantiation limit

packages/nextjs/utils/scaffold-eth/contract.ts
Rather than just check if `deployedContracts` is `null`, this improves the behavior to check if there is a contract definition for the network selected in `scaffold.config.ts`. This results in fewer type errors when a contract might have been deployed on some network, but locally a user only has the file generated for another network.
Fixes #371
=> fix(contract.ts): improve missing config check

packages/nextjs/utils/scaffold-eth/contract.ts
When you are using arguments values from `listner`  in `useScaffoldEventSubsciber` and if the `deployedContract = null` it gives the error : 
Similar to other hooks it should resolve to `any` when `deployedContract = null`  
=> fix listner types error when contracts missing

packages/hardhat/.gitignore, packages/hardhat/hardhat.config.ts, packages/hardhat/package.json, yarn.lock
Configuration for deploying on zkSyncTestnet.
According to the [zkSync docs](https://era.zksync.io/docs/tools/hardhat/migrating-to-zksync.html#deploy-contracts), hardhat-deploy version ^0.11.26 supports deployments on zkSync Era.
Therefore I've upgraded hardhat-deploy to 0.11.26.
Also, zkSync uses their own "hardhat-zksync-solc" compiler, which has to be imported in hardhat.config.ts.
After these changes, I could deploy to zkSyncTestnet with **yarn deploy --network zkSyncTestnet** and I could interact with the demo YourContract when I switched the targetNetwork to chains.zkSyncTestnet in [scaffold.config.ts](https://github.com/scaffold-eth/scaffold-eth-2/blob/9faa67540a264accf71cf03bd8dd89b06b6a4c36/packages/nextjs/scaffold.config.ts#L16).
Let me know if you have any questions.
Best, …
=> zkSyncEra Testnet config

packages/nextjs/components/example-ui/ContractInteraction.tsx, packages/nextjs/hooks/scaffold-eth/useScaffoldContractWrite.ts
Sometimes there is a situation where you need to calculate some stuff just before calling `writeAsync` and currently I think there is no way to pass that calculated value as args  before calling the function (are there any good ways of doing this ?)
Current non-working example : 
```javascript
const [uploadedItemHash, setUploadedItemHash] = useState("")
const { writeAsync: mintItem } = useScaffoldContractWrite({
...,
args : [connectedAddress,uploadedItemHash] 
// here the args are not updated while calling the writeAsync
});
const handleMintItem = async () => {
const uploadedItem = await ipfsClient.add(JSON.stringify(currentTokenMetaData));
setUploadedItemHash(uploadedItem.path)
await mintItem();
}  
```
New Working example : 
```javascript
const { writeAsync: mintItem } = …
```
=> update writeAsync to take in updated args while calling it

packages/nextjs/package.json, packages/nextjs/scaffold.config.ts, packages/nextjs/services/web3/wagmiConnectors.tsx, yarn.lock
Updated wagmi and rainbowkit there were close to no breaking changes and were only related to WalletConnect in both wagmi and rainbowkit checkout -> [wagmi migration from 0.11.x -> 0.12.x](https://0.12.x.wagmi.sh/react/migration-guide#012x-breaking-changes) and [rainbow kit migration guide](https://www.rainbowkit.com/docs/migration-guide#012x-breaking-changes)
**Demo** : 
https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/fedafa28-d22c-4780-9397-1d70fe2c0a95
**TODO** : 
None
=> update wagmi & rainbow for walletConnectV2

packages/nextjs/tailwind.config.js
This pull request changes the scaffoldEthDark secondary color from #2A3655 to #323f61.
Please refer to this issue for more information about the problem: [https://github.com/scaffold-eth/scaffold-eth-2/issues/397](url)
_Closes #{397}_
Your ENS/address: portdev.eth
=> Change scaffoldEthDark secondary color from #2A3655 to #323f61

packages/foundry/package.json
Resolve Foundry 'yarn deploy' and 'yarn deploy:verify' module not found error
In packages/foundry/package.json
Change the script name from 'generateTsAbis.ts' (.typescript) to 'generateTsAbis.js' (.javascript)
- See Discussion here: https://github.com/scaffold-eth/scaffold-eth-2/issues/394#issuecomment-1618272065
=> Resolve Foundry 'yarn deploy' and 'yarn deploy:verify' module not found error

packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts, packages/nextjs/hooks/scaffold-eth/useScaffoldEventSubscriber.ts
Typescript has issues to infer the type of the `part` variable in the `find` call because the array is `readonly [...] | readonly [...]`. Since we don't depend on the actual inferred type in this internal hook, we can just assert the abi to it's general `Abi` type.
The other type issue in `eventSubscriber` is similar. Typescript can't infer which of the two abis is to be used in the `useContractEvent` call, and thus doesn't understand that the `eventName` should always be valid. It's possible that a more complex method exists to make typescript infer a more narrow abi, but since it's just internals and is passed down to `useContractEvent`, I think the proposed fix more than suffices. The types that are exposed (param and return type) work fine, so shouldn't really be of concern to the …
=> fix: type issues when multiple contracts deployed

src/tasks/copy-template-files.ts
Fix a bug that made `copyExtensionsFiles` work async, so when later code tried to access extension files, they weren't there yet. That caused a bug with `findFilesRecursiveSync`, where files that should've been found weren't returned.
=> Fix bug with findFilesRecursiveSync

packages/nextjs/package.json, yarn.lock
Locked the version of `viem` and `wagmi` is obviously not the best solution 
I have also raised the issue on https://github.com/wagmi-dev/wagmi/issues/2736
Maybe we can also wait until they fix it....just wanted to reference this fix for #419 if anyone gets stuck 🙌
=> lock the version of viem and wagmi

src/utils/render-outro-message.ts
`foundryup --version` make an http request and it can be slow. `foundry -h` solves the same problem and it's instant.
=> Change foundryup command

README.md, packages/hardhat/.env.example, packages/nextjs/.env.example
This PR adds .env.example file for nextjs environment variables, like we already have for hardhat.
Also adds some extra information on how we are managing API Keys in config/env files in both hardhat and nextjs .env.example files, so users can have a better understanding.
Your ENS/address: pabl0cks.eth
=> Add .env.example for nextjs env variables

package.json
This is one of the historical commands, and I think it should be there. Instead of calling the command on packages/hardhat, I'm calling `hardhat:test` so it becomes clear that it's an alias.
This could become `hardhat:test && nextjs:test` in the future... an alias to run both test suites (if we do some https://github.com/Synthetixio/synpress testing in the frontend at some point)
Also, I can't handle the pressure of @austintgriffith calling me at 3am for this (jk jk <3)
**Note:** If you all are ok with this, we should also do it in the cli branch (for hardhat / foundry)
=> Create an alias for hardhat:test

packages/nextjs/pages/debug.tsx
We get a blank debug page, this happens when there is a value in localStorage that does not match any of newly deployed contractNames 
Added a `useEffect` which checks if the current localStorage value is present in `contractNames`array and returns 0th contractName if it doesn't find any match
=> fix empty debug page  when mismatch in localStorage and contractName

templates/base/packages/nextjs/pages/blockexplorer/address/[address].tsx
The UI breaks for `blockexplorer/[address]` in `foundry` extension since we have hardcoded `hardhat` in `[address].tsx` 
Should we add this to `main` and `foundry` branch too 🤔?
=> use targetNetwork instead of hardcoding dir name in template root

packages/nextjs/components/scaffold-eth/Faucet.tsx, packages/nextjs/components/scaffold-eth/FaucetButton.tsx
Since we have `localWalletClient` as use effect dependency we get lot of `eth_accounts` because of this line : https://github.com/scaffold-eth/scaffold-eth-2/blob/6370b4c49440f4aab7eff6896b43d814d6d01650/packages/nextjs/components/scaffold-eth/Faucet.tsx#L35
You can easily notice lot of `eth_accounts` while using SE-2 through CLI but for some reason on `main` it sometimes doesn't happens directly and if you add `console.log("This is localWalletClient", localWalletClient)` below the above `permalink` it will start making `eth_accounts` (😅 even I am confused about this behavior on `main` but I noticed on it on main)
Nevertheless, I think it makes  sense not to pass objects as dependency to `useEffect` 
Move `localWalletClient` outside of the component this we don't need to pass it as a …
=> fix eth_accounts calls on localNetwork

packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx, packages/nextjs/tailwind.config.js, packages/nextjs/utils/scaffold-eth/notification.tsx
Fixes #441 
I discussed several options with Andrea, to make the dropdown / notifications look better (they were mixing with the background).
We ended up adding a new shadow utility class `shadow-center` that combined with a `shadow-accent` (or `shadow-{primary|secondary|etc..}) gives a nice effect.
Notifications:
Dropdown menu: (Also made the dropdown menu items smaller and adjust the border radius (we can also apply this to #446))
What do you all think?
=> New shadow-center utility class for dropdown/notifications

packages/nextjs/components/scaffold-eth/Input/AddressInput.tsx, packages/nextjs/components/scaffold-eth/Input/Bytes32Input.tsx, packages/nextjs/components/scaffold-eth/Input/BytesInput.tsx, packages/nextjs/components/scaffold-eth/Input/EtherInput.tsx, packages/nextjs/components/scaffold-eth/Input/InputBase.tsx, packages/nextjs/components/scaffold-eth/Input/IntegerInput.tsx, packages/nextjs/components/scaffold-eth/Input/utils.ts
Moves `disabled` prop to `CommonInputProps`, so it becomes possible to disable all inputs,  not only `InputBase`
Your ENS/address: 0xrinat
=> fix: moved disabled to commonInputProps

packages/nextjs/components/scaffold-eth/Faucet.tsx, packages/nextjs/components/scaffold-eth/FaucetButton.tsx, packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx, packages/nextjs/hooks/scaffold-eth/index.ts, packages/nextjs/hooks/scaffold-eth/useAutoConnect.ts, packages/nextjs/services/web3/wagmiConfig.tsx
Proposing a hacky but minimal and working solution after many tries 😅
It seems that Wagmi maintains a localStorage too for the last connected wallet in the key `"wagmi.wallet"` I just latched on it as intial value for our localStorage key `"scaffoldEth2.wallet"` . 
I have also put back `useAutoConnect` because it seems to solve hydration errors while using other hooks too like `useNetwork` (that's why there was a need of adding `useIsMounted` in Faucet and faucetButton in #412)
Fixes #453 
=> Fix/useAccount & some other hooks hydration issue 

packages/nextjs/utils/scaffold-eth/contract.ts
While reviewing the types in `contract.ts` (the best way to learn TypeScript advanced features :D), I realized that some of the types aren't being used.
=> Remove unused types

packages/hardhat/hardhat.config.ts, packages/hardhat/scripts/generateAccount.ts
1. Show generated address when you run `yarn generate`
2. Add gnosis and Chiado, we recently added them in foundry at #469, also was mentioned in #481 
NOTE: It does not solve #481 completely
=> Add address log for generated wallet & gnosis, chiado in hardhat config

README.md, src/tasks/create-first-git-commit.ts, templates/base/packages/nextjs/components/scaffold-eth/Contract/ReadOnlyFunctionForm.tsx, templates/base/packages/nextjs/hooks/scaffold-eth/useScaffoldContract.ts, templates/extensions/foundry/packages/foundry/package.json, templates/extensions/foundry/packages/foundry/remappings.txt, templates/extensions/foundry/packages/foundry/script/Deploy.s.sol, templates/extensions/foundry/packages/foundry/script/DeployHelpers.s.sol, templates/extensions/foundry/packages/foundry/script/generateAccount.js, templates/extensions/hardhat/packages/hardhat/hardhat.config.ts, templates/extensions/hardhat/packages/hardhat/scripts/generateAccount.ts
1. Foundry Updates(#475 ) : 
a. We have put back `yarn deploy --network network_name` command similar to hardhat
b. Adds openzepplin by default with installation 
c. Updated deploy scripts to solve pt.5 of https://github.com/scaffold-eth/scaffold-eth-2/issues/470#issue-1832581912
2. Some changes from `main` branch : 
a. Remove unused types (#465)
b. autocompletion for useScaffoldContract (#460 )
c. fix styles for read contract in debug page (#478 )
=> backmerge recent updates into CLI 

packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx
Fixes RainbowKitCustomConnectButton dropdown styles
before:
wrong alignment
Copy address line is overlapped by grab faucet message
after:
0xrinat
=> Fix RainbowKitCustomConnectButton dropdown styles

packages/nextjs/components/Footer.tsx, packages/nextjs/pages/index.tsx
Removed the padding-x so as to have greater space on mobile screens (updated version #501 ) : 
fixes #497 
=> chore: footer missalignment on mobile screens

packages/hardhat/package.json, packages/nextjs/next.config.js, packages/nextjs/package.json, packages/nextjs/types/abitype/abi.d.ts, yarn.lock
So after a lot of digging, I landed on [how to two versions of same npm package](https://stackoverflow.com/questions/43770328/two-versions-of-same-npm-package-in-node-application) and for some reason, I am not able to find that particular link but people were trying to have kind of same typescript version. Which led to me thinking that the reason  `yarn next:check-types` might be checking `node_modules` as discussed in #492 is because `viem` is using typescript version `5+` 
So the steps I followed to fix #492  : 
1. Updated `viem` version to latest using `yarn workspace @se-2/nextjs up viem`
2. I did `yarn next:check-types` here I got `678 errors` mostly from `node_modules/viem`
3. `yarn workspace @se-2/nextjs up typescript` (For some reason this also updated hardhat typescript version …
=> Update and typescript version

package.json, packages/subgraph/graph-node/docker-compose.yml, packages/subgraph/package.json
I updated the package.json as well as the docker-compose configuration to hard code graph-node version. We experienced some users having issues with a cached version and broke graph cli functionality
_Closes N/A
=> Subgraph package

packages/nextjs/components/Header.tsx
This is a hacky solution for #509
=> add grid and grid-flow class to li manually

packages/nextjs/hooks/scaffold-eth/useScaffoldContractWrite.ts
Fixes two typos in getScaffoldContractWrite.ts lines 57 & 65
_Closes #511 
Your ENS/address: zakgriffith.eth
=> Fix typos in getScaffoldContractWrite lines 57 & 65

packages/foundry/package.json
Addresses issues #524 
_Closes #524
Your ENS/address: jrcarlos2000.eth
=> foundry: add chain id 31337 while forking chain

packages/nextjs/components/example-ui/ContractInteraction.tsx, packages/nextjs/hooks/scaffold-eth/useScaffoldContractWrite.ts, packages/nextjs/utils/scaffold-eth/contract.ts
As discussed in https://github.com/scaffold-eth/scaffold-eth-2/discussions/516, I agree with the discussion and also makes sense now 🙌
also btw the type of `value` that we had was a bit too harsh as it was typed as `${number}` lol which was a PITA to get it right until you write your own validate function helper or assert it with `as` or just pass in literal value like "0.1".
Here is an example that might frustrate users: 
Nevertheless, this PR removes `parseEther` from `useScaffoldContractWrite` so we leave it to users, which solves all the issue 🙌
=> remove `parseEther` from useScaffoldContractWrite

packages/nextjs/components/Footer.tsx, packages/nextjs/tailwind.config.js
Changes so that the Footer uses `link` from tailwind. Also adding some customization to it.
Implements the feedback from @carletex here: https://github.com/scaffold-eth/scaffold-eth-2/pull/551
Your ENS/address: harmont.eth
=> make use of tailwind `link`-class with some extensions

packages/nextjs/components/scaffold-eth/Input/AddressInput.tsx, packages/nextjs/components/scaffold-eth/Input/utils.ts
Treat any dot-separated string as a potential ENS name rather than hardcode a few TLDs, [as suggested by the ENS docs](https://docs.ens.domains/dapp-developer-guide/resolving-names)
Closes https://github.com/scaffold-eth/scaffold-eth-2/issues/562
Your ENS/address: gregskril.eth
=> Improve ENS support (accept all TLDs)

packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
Return `data` from `useScaffoldEventHistory` is not memoized. So because of `.map` it returns new array on every render even when `events` doesn't change
This pr fixes it
0xrinat
=> Memo history events

README.md, package.json
Added the `repository` prop to `package.json` so it shows the link on the npmjs package sidebar.
---
Also updated the README to have a link to the CLI branch.
=> Package.json repo url + README link to CLI branch

packages/nextjs/components/Header.tsx
Fixes https://github.com/scaffold-eth/scaffold-eth-2/issues/568
Same as #569 but inlining the menu array (instead of extracting it to a diff file)
=> Extract headerMenuLinks from Header (inline variation)

packages/nextjs/components/Footer.tsx, packages/nextjs/components/Header.tsx, packages/nextjs/components/scaffold-eth/Faucet.tsx
For the sake of cleaning up the UI a bit (Example UI might be next :D Will create an issue soon), I'm testing moving the Block Explorer from the main menu to the footer. You still have access in any page (+ in the TX notifications) but in a less intrusive way. It will only show on dev env (local network), like the Faucet.
---
Anyway, just tinkering. Let me know what you think!
=> Move Block Explorer to footer

packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx, packages/nextjs/hooks/scaffold-eth/useScaffoldContractWrite.ts
In summary, we get this error : 
While sending `value` i.e greater than our wallet balance, Ideally it should have given us "Sender doesn't have enought fund...." error  
Check out https://github.com/wagmi-dev/wagmi/issues/3155 for full context
Removing `chainId` from `useContractWrite` solves this problem, We could also wait until https://github.com/wagmi-dev/wagmi/issues/3155 is fixed and close this 🙌
=> fix: incorrect error when sending txn with insufficient funds 

packages/nextjs/components/scaffold-eth/Contract/TxReceipt.tsx
Add copy to clipboard to transaction receipt to allow to copy the transaction data easily.
=> Add copy to clipboard to TxReceipt

packages/nextjs/pages/blockexplorer/transaction/[txHash].tsx
Add event logs to the transaction page.
I added only the topics since I think all the important log information is already on the transaction data. Please let me know if you think I should add something more. 
We should try to show the topics information in a prettier way, adding the event name and the parameters names, and decoding the data. Here and in the contract logs page too, but this is for another issue ;-)
=> Add event logs to transaction page

packages/nextjs/utils/scaffold-eth/contract.ts
When a contract function returns an array only the first element type was returned when using the useScaffoldContractRead hook.
Now all the types from the array are returned.
I'm not sure if this breaks something else... AbiFunctionReturnType is only used on useScaffoldContractRead hook and everything seems to be working fine.
=> Fix AbiFunctionReturnType removing [0]

packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts, packages/nextjs/utils/scaffold-eth/contract.ts
Add a new poolingInterval optional parameter to useScaffoldEventHistory to be able to get the new events. 
If we merge this PR, I will open a PR to update the doc.
=> Add pooling interval to EventHistory hook

packages/nextjs/components/scaffold-eth/Input/IntegerInput.tsx
Add multiplyBy1e18Enabled flat to IntegerInput component. 
When this flag is set to false, the button to multiply the number by 1e18 is not shown. This is to be used when doesn't make sense to multiply the user input by that amount, like when it's used to enter a regular number.
The default value is true, so the default behavior is not changed.
=> Add multiplyBy1e18Enabled flat to IntegerInput component

packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
The events are sorted by new ones first, so the newEvents should be added in front of the old events.
=> Fix useScaffoldEventHistory hook new events order

packages/nextjs/hooks/scaffold-eth/useScaffoldContractWrite.ts, packages/nextjs/hooks/scaffold-eth/useTransactor.tsx
This PR adds ```(() => Promise<`0x${string}`>)``` to tx types on useTransactor to allow them to be called using a contract.write.method. 
For example:
```
const writeTx = useTransactor();
const { data: walletClient } = useWalletClient();
const { data: yourContract } = useScaffoldContract({
contractName: "YourContract",
walletClient,
});
const setGreeting = async () => {
if (yourContract !== undefined) {
const makeWrite = () => yourContract.write.setGreeting(greeting);
await writeTx(makeWrite, {
onBlockConfirmation: txnReceipt => {
console.log("Transaction blockHash", txnReceipt.blockHash);
},
});
}
}
```
Please, let me know if you think this is useful or is there a better way to do this.
=> Allow to use useTransactor hook with contract.write.method

packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts, packages/nextjs/utils/scaffold-eth/contract.ts
Add requiredFilters param to useScaffoldEventHistory hook to avoid getting wrong events when setting a filter that is not yet populated with the right value.
If one of the requiredFilters is not set, the hook returns an error.
For example, if I get the filter value from the router query, the first value is undefined, and the hook will return all the events, without this filter applied.
To fix it, I can use a useEffect hook, something like this:
```
const { roomHash } = router.query as { roomHash: 0x${string} };
const [roomHashFilter, setRoomHashFilter] = useState<string>("aa");
useEffect(() => {
if (roomHash) {
setRoomHashFilter(roomHash);
}
}, [roomHash]);
const {
data: roomJoinEvents,
isLoading: isLoadingRoomCreateEvents,
error: errorReadingRoomCreateEvents,
} = …
```
=> Add requiredFilters param to useScaffoldEventHistory hook

packages/hardhat/hardhat.config.ts, packages/nextjs/package.json, yarn.lock
Nicely tested the whole app and everything works great 🙌
Here is the test `Index.ts` page file : 
<details>
<summary>
Test file with main hooks and imperative read/write examples  : 
</summary>
```tsx
import { useEffect } from "react";
import Link from "next/link";
import { parseEther } from "viem";
import { useAccount, useWalletClient } from "wagmi";
import { BugAntIcon, MagnifyingGlassIcon } from "@heroicons/react/24/outline";
import { MetaHeader } from "~~/components/MetaHeader";
import { Address } from "~~/components/scaffold-eth";
import {
useScaffoldContract,
useScaffoldContractRead,
useScaffoldContractWrite,
useScaffoldEventHistory,
} from "~~/hooks/scaffold-eth";
const { address: connectedAddress } = …
```
=> update wagmi, viem and rainbowkit versions

packages/nextjs/components/blockexplorer/AddressStorageTab.tsx, packages/nextjs/components/scaffold-eth/Address.tsx, packages/nextjs/components/scaffold-eth/Balance.tsx, packages/nextjs/components/scaffold-eth/Contract/utilsDisplay.tsx, packages/nextjs/components/scaffold-eth/Faucet.tsx, packages/nextjs/components/scaffold-eth/Input/AddressInput.tsx, packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/AddressInfoDropdown.tsx, packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/AddressQRCodeModal.tsx, packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/index.tsx, packages/nextjs/hooks/scaffold-eth/useAccountBalance.ts, packages/nextjs/pages/blockexplorer/address/[address].tsx, packages/nextjs/pages/blockexplorer/transaction/[txHash].tsx, packages/nextjs/scaffold.config.ts, packages/nextjs/types/abitype/abi.d.ts, packages/nextjs/utils/scaffold-eth/fetchPriceFromUniswap.ts
I aligned all addresses to use the Address type of viem (see #617).
Also added a config option for a dev to use more strict Address if he wants additional typesafety (default is current behavior where addresses are typed as `string`).
(This also basically fixes #514 by making it optional, with a sensible default)
=> fix(address type): allows user to set his preference in scaffold config

packages/nextjs/scaffold.config.ts, packages/nextjs/types/abitype/abi.d.ts
Fixes #640 for now, this removes the ability for the users to configure `AddressType` from `scaffold.config.ts` until we properly find a way to handle it (without having type error) 
Maybe we can merge this for now since #640 is kind of blocker for people deploying on other networks / using multi-chain
=> patch scaffoldConfig type error

packages/hardhat/deploy/99_generateTsAbis.ts
I ran into some problems when importing the open-zepline  ERC721 contract.
Trying to import this:
Having this error when deploying at the moment it runs the 99_generateTsAbis.ts script:
In these lines, it tried to look for ERC721 in available entries (sources), however, it found IERC721 before the actual ERC721.
So he resolved with the path of IERC721 instead.
Looking for the exact path segment using '/' as prefix for includes argument did the job:
E.g. Looking for `/ERC721` in 
[
"@openzeppelin/contracts/interfaces/IERC721.sol",
"@openzeppelin/contracts/token/ERC721.sol"
]
Only the second entry matched this time (expected one).
Your ENS/address: Gossman.eth
=> Contract Deploy - Check for exact path segment when extracting contract path in artifacts

packages/nextjs/components/scaffold-eth/Contract/ContractReadMethods.tsx, packages/nextjs/components/scaffold-eth/Contract/ContractVariables.tsx, packages/nextjs/components/scaffold-eth/Contract/ContractWriteMethods.tsx, packages/nextjs/components/scaffold-eth/Contract/DisplayVariable.tsx, packages/nextjs/components/scaffold-eth/Contract/ReadOnlyFunctionForm.tsx, packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx, packages/nextjs/components/scaffold-eth/Contract/utilsContract.tsx, packages/nextjs/utils/scaffold-eth/notification.tsx
This problem occurs when you have custom solidity errors and you try to read/write from Debug page : 
<details>
<summary> Test YourContract.sol </summary>
```solidity
//SPDX-License-Identifier: MIT
pragma solidity >=0.8.0 <0.9.0;
// Useful for debugging. Remove when deploying to a live network.
import "hardhat/console.sol";
error NOT_OWNER();
error MY_CUSTOM_ERROR(string message, uint value);
contract YourContract {
// State Variables
address public immutable owner;
string public greeting = "Building Unstoppable Apps!!!";
uint256 public totalCounter = 0;
constructor(address _owner) {
owner = _owner;
}
modifier isOwner() {
if (msg.sender != owner) {
revert NOT_OWNER();
}
_;
}
function revertWithCustomErrror(bool _shouldRevert) public view {
if (_shouldRevert) {
revert MY_CUSTOM_ERROR( …
```
=> Fix displaying of custom solidity errors

packages/nextjs/components/scaffold-eth/Contract/utilsContract.tsx
https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/7bb60bf3-ddb8-4b16-a527-d0988ee62ef7
Noticed while testing #648 and was introduced in #638 my bad 🤦‍♂️ 
I will also raise an issue on VIem so that in the future we don't need to assert typing manually and get proper typing from it directly when narrowed through `ContractFunctionExecutionError`
=> patch: add check before accessing `cause.data` in getParsedError

packages/nextjs/package.json, yarn.lock
It looks lke the LedgerConnector (@ledgerhq/connect-kit-loader) has been compromised
Context:
https://twitter.com/wevm_dev/status/1735289737185837303
https://twitter.com/bantg/status/1735279127752540465
----
We don't use it on SE2 (we just use Rainbow's kit LedgerWallet) so we should be fine.
In any case, updating wagmi with the last version (where they remove the dependency): https://github.com/wevm/wagmi/commit/53ca1f7eb411d912e11fcce7e03bd61ed067959c
=> Update wagmi to latest version

packages/nextjs/services/web3/wagmiConnectors.tsx
This allows any app to iframe in SE-2 and connect. 
For example : [impersonator.vision](https://impersonator.vision/)
Also tested it nicely even with safe iframe and works great everywhere. This PR just removes extra options that we had and keeps it default.
Here is the option's documentation: https://github.com/safe-global/safe-apps-sdk/tree/main/packages/safe-apps-sdk#documentation
test app link: https://ifram-any.vercel.app
Thanks to @austintgriffith for suggestion 🙌
=> use default values for safeConnector

README.md, packages/nextjs/app/page.tsx
These two changes are not related at all, but they were very small, and creating 2 PRs felt like overkill. Changes added:
- Closes #689 
- Closes #690 
Your ENS/address: pabl0cks.eth
=> Update homepage file route in the home instructions and add Viem to Readme tech stack

packages/hardhat/deploy/00_deploy_your_contract.ts, packages/hardhat/package.json, packages/hardhat/scripts/listAccount.ts, packages/hardhat/test/YourContract.ts, yarn.lock
Recently we updated all the hardhat related packages in #637, but it seems that if you uncomment : 
https://github.com/scaffold-eth/scaffold-eth-2/blob/e4c70071ae804f88d4d73662d8e1b52ea7e833bd/packages/hardhat/deploy/00_deploy_your_contract.ts#L35
You get an error, which I think is caused due to `hardhat-deploy-ethers` and `hardhat-ethers`  digging few discussion it seems that updating ethers to v6 does seems to solve this issue due to some internal api changes
=> Ethers v6 migration in hardhat

packages/nextjs/components/scaffold-eth/Input/index.ts
This was introduced in #688 which we recently merged. We removed "use client" from components like `AddressInput`, `EtherInput` etc in #688 because there was lint warning in them as mentioned in #686. 
If you look at the error it occurred at `blockexplorer/address/[address]/page.tsx` and the cause of the error is `AddressInput`, but we are not using `AddressInput` anywhere instead we are using `Address` component which comes from `~~/components/scaffold-eth/index.ts` barrel file and since this barrel file also exports inputs barrel we are indirectly importing `AddressInput` in address page (although we are not using it). 
I would suggest going through this comment discussion https://github.com/vercel/next.js/discussions/46795#discussioncomment-5248407 once its really nice. 
For now, I …
=> fix broken blockexplorer address page

packages/hardhat/hardhat.config.ts
arbitrumGoerli is not working for yarn verify
_Closes #715 
This is the change for subgraph-package
=> changing hardhat.config.ts to arbitrumSepolia instead of arbitrumGoerli

packages/hardhat/hardhat.config.ts, packages/nextjs/utils/scaffold-eth/networks.ts
Optimism testnet migrated from Optimism Goerli to Optimism Sepolia early this year, as per this [announcement](https://blog.oplabs.co/op-sepolia/). The [testnet faucets](https://app.optimism.io/faucet) now all drip Sepolia. Proposing this PR to keep up with this migration. 
Your ENS/address: winnster.eth
=> Add Optimism Sepolia config

packages/hardhat/hardhat.config.ts, packages/nextjs/utils/scaffold-eth/networks.ts
arbitrumGoerli is not working with yarn verify and I'd expect will go EOL soon.
_Closes #715
=> changing hardhat.config.ts to arbitrumSepolia instead of Goerli

packages/nextjs/package.json, yarn.lock
It seems that there was some changes related to i18-js, which was fixed at [@rainbow-me/rainbowkit@1.3.4](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%401.3.4) so updated to 1.3.5(which is latest 1.x version) and it does seem to solve the issue 
fixes #718
=> up rainbowkit version to 1.3.5

packages/nextjs/app/debug/_components/contract/ContractInput.tsx, packages/nextjs/app/debug/_components/contract/Tuple.tsx, packages/nextjs/app/debug/_components/contract/TupleArray.tsx, packages/nextjs/app/debug/_components/contract/WriteOnlyFunctionForm.tsx
First iteration on #725 
This odd padding won't let me sleep haha (also making sure the inner structs padding looks good too)
Now: 
As Shiv mentioned, maybe it's a good idea to have a label on the value input too.
In the current version, the text felt a bit "lost"
Made a couple of tweaks:
1. add some background
2. Add a border. If not, the inner struct will have the same problem (its background is the same as the parent bg). A border fixed it
----
We can add more stuff here, or keep iterating in another PR.
=> improve debug struct UI

packages/nextjs/components/scaffold-eth/Input/AddressInput.tsx, packages/nextjs/components/scaffold-eth/Input/InputBase.tsx
- We have debounce time of 500ms for the input field.
- Actually we have isEns util which when true (carletex.e is valid ens), the hook useEnsAddress makes a request for corresponding ENS address
- We are disabling the input filed when the request is in progress.
- Input focus looses when its is disabled (it does not regain focus when enabled again)
1. Since we have 500ms debounce time, as soon as you write carletex.e (valid ens), the request is made and input is disabled.So if there is delay >= 500ms b/w "e" & "t" of "eth" then input looses focus(and our key strokes are not registered).
1. Increase the debounce time to 900ms (So we give user a bit more window to type in "eth").
2. Incase the user is slow typer, We refocus the input after trying to resolve the ens address.
1. Show …
=> Fix cursor stealing & display loading for AddressInput

packages/nextjs/app/blockexplorer/address/[address]/page.tsx
Actually in #734, we are now using ERC-55 [checksum](https://viem.sh/docs/utilities/getAddress) format in address because of which `contractInfo.address.toLowerCase() === address` was failing and we were displaying empty thing in `code tab` of blockexplorer
| Before | After | 
| ------- | ----- | 
| ![Screenshot 2024-02-26 at 8 33 49 PM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/d26735d8-adc9-434a-8785-9f14ee8801b5) | ![Screenshot 2024-02-26 at 8 34 33 PM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/62484011-a89d-4d1e-87f2-a715fde04a70) | 
Noticed this while testing #740
=> fix contract code tab in blockexplorer

packages/nextjs/app/page.tsx
This PR changes Debug Contract to Debug Contracts in the homepage card since the actual tab name is "Debug Contracts".
Before:
After:
_Closes #{issue number}_
Your ENS/address: portdev.eth
=> Match link name with actual tab name in Homepage

package.json, packages/hardhat/package.json
`yarn flatten`: Allow to flatten contracts into a single file.
I think we could do the same in Foundry: https://book.getfoundry.sh/reference/forge/forge-flatten
Open to suggestions!
=> yarn flatten

.changeset/silly-coins-share.md, src/main.ts, src/tasks/index.ts, src/tasks/prettier-format.ts, templates/base/package.json, templates/extensions/foundry/package.json, templates/extensions/foundry/packages/foundry/.prettier.json, templates/extensions/foundry/packages/foundry/contracts/YourContract.sol, templates/extensions/foundry/packages/foundry/foundry.toml, templates/extensions/foundry/packages/foundry/package.json, templates/extensions/foundry/packages/foundry/script/Deploy.s.sol, templates/extensions/foundry/packages/foundry/script/DeployHelpers.s.sol, templates/extensions/foundry/packages/foundry/script/VerifyAll.s.sol, templates/extensions/foundry/packages/foundry/script/generateTsAbis.js, templates/extensions/foundry/packages/foundry/test/YourContract.t.sol, templates/extensions/hardhat/package.json, templates/extensions/hardhat/packages/hardhat/package.json
Since we have `.template.mjs` file eg [this](https://github.com/scaffold-eth/scaffold-eth-2/blob/cli/templates/base/packages/nextjs/app/blockexplorer/address/%5Baddress%5D/page.tsx.template.mjs). So when the whole project is scaffolded there are some prettier warning left for eg:  #748 logs. 
This PR: 
- Adds base `format` script in root package.json to format both hardhat and foundry
- Adds a new task  "🪄 Formatting files with prettier" to cli
- For foundry 
- Added [fmt] in foundry.toml kindof inline with our hardhat configuration to format solidity files, formated .sol file with `forge fmt`
- Formated `.js` file with prettier also added `.prettier.json` in `packages/foundry`
=> Cli add prettier task

packages/hardhat/contracts/YourContract.sol, packages/subgraph/README.md
Fixing the value emitted from the greeting to be `msg.value`
NA
=> Subgraph package - fix event emit to properly use msg.value and not "0"

packages/nextjs/hooks/scaffold-eth/useScaffoldContractWrite.ts, packages/nextjs/hooks/scaffold-eth/useTransactor.tsx
- These changes reflect what is summarized at the bottom of issue #753
- Added line 88 to useScaffoldContractWrite.ts and changed line 98 in useTransactor.tsx
- These changes throw errors forward to a function utilizing useScaffoldContractWrite, and removes one notification error to prevent duplicate error notifications displaying.
- I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)
_Closes #753_
Your ENS/address:  zurriken.eth
=> Fix useScaffoldContractWrite so it properly throws errors

.gitignore, package.json, packages/nextjs/package.json, vercel.json, yarn.lock
My 99th try of trying to fix this. 
context #419 and all referenced PR inside it. 
Obviously there is a catch, had to add `next` as devDependency of monorepo because of https://github.com/orgs/vercel/discussions/6047 but now atleast it uploads whole monorepo (mainly `yarn.lock`) which fixes all the issues
Work flow doesn't change at all you just need to choose all defualt options and add vercel project : 
https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/32a76d20-c6e2-49fc-9072-bdac9f7a947b
=> Fix vercel deployment mismatch

packages/nextjs/app/debug/_components/contract/WriteOnlyFunctionForm.tsx, packages/nextjs/components/scaffold-eth/Faucet.tsx
Noticed this while testing #756, it was caused in #758 : 
https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/b85785fb-594e-4a9d-992c-17004c04a553
When you get an error while sending transaction, it shows notification two times, this is due to since in #758, we are not eating up error in `useTransactor` instead showing notification + throwing it forward. 
In 27468772f82636bbbdf7ebf04e5299094a3bd38d removed our own showing of notification or error again since its same already shown in `useTransactor`
For more details checkout : https://github.com/scaffold-eth/scaffold-eth-2/pull/758#pullrequestreview-1921719734
=> remove extra notifications when using useTransactor

.vercelignore, packages/nextjs/.gitignore
It's sad that Vercel don't respect `.gitgnore` inside it each package of monorepo, it was even uploading `.env` of hardhat :( : 
--- 
Also vercel doesn't respect `.vercelignore` inside each package, so had to copy all the things from each package `.gitignore` and append `packages/{packageName}` in `.vercelignore` at the root
Not sure what would be the better approach 
Here are docs : 
https://vercel.com/docs/deployments/vercel-ignore
Fixes #767
=> add .vercelignore

packages/nextjs/app/layout.tsx
Pulls out the shared `title` `template` and `description` from the `layout.tsx` metadata and make them into variables. This is just a small change to help reduce redundancies in the metadata object.
=> Extract metadata title and description

packages/hardhat/deploy/00_deploy_your_contract.ts, packages/hardhat/hardhat.config.ts, packages/nextjs/utils/scaffold-eth/networks.ts
Goerli has been effectively deprecated and is no longer supported by major RPC clients, thus we can safely remove it from the template as it appears as unnecessary fluff.
- [ x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)
Your ENS/address: JacobHomanics.eth
=> Remove Goerli from supported networks

src/main.ts, src/tasks/prettier-format.ts
Fixes #783, This is kind of short-term solution for now since if you skip install dependency it will not install prettier, which in turn will not format files. 
We added a prettier formatting file task because we get a prettier warning : 
Also checkout #750 for more context 🙌
=> cli: skip prettier formatting if install dependency is skipped

packages/nextjs/app/blockexplorer/_components/AddressCodeTab.tsx
This reformats the assembly view so it keeps hex characters (`PUSH` parameters) on the same line.
Before:
(Notice how there's a newline between the `PUSH1` and `0xE0`)
After:
(Now, `PUSH1` and `0xE0` are on the same line).
N/A
Your ENS/address: `0x598cb95773D9b66a27a5780DB5EED2d018685879`
=> Reformat assembly display in AddressCodeTab

packages/nextjs/.gitignore
Add .env to .gitignore in nextjs package #797 - Although Next [docs](https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#default-environment-variables) has this and makes complete sense. But sometimes people tinkering with both hardhat and nextjs package might loose the context and add secrets to .env in nextjs assuming it is gitignored similar to hardhat pacakge
Discussed with @technophile-04 on telegram
_Closes #797 _
Your ENS/address: websculpt.eth
=>  Add .env to .gitignore in nextjs package #797

packages/nextjs/package.json, packages/nextjs/tailwind.config.js, yarn.lock
Tailwind offers the `dark` variant (same as `hover:`, etc) https://tailwindcss.com/docs/dark-mode, but it didn't work because we didn't have it properly configured. Since it's super easy to enable, I think we should have it in!
I updated TW to the latest version since it wasn't working with the current one:
----
To test, you can just copy paste this piece into the homepage (page.tsx). Note the `dark:bg-red-500`
```tsx
<code className="italic bg-base-300 dark:bg-red-500 text-base font-bold max-w-full break-words break-all inline-block">
packages/nextjs/app/page.tsx
</code>
```
---
I had to restart the nextjs server (yarn start) to make it work after (yarn install)
=> Tailwind dark variant working

README.md
Previously the main frontend path was `nextjs/pages`. Now the project switched to the Next.js App Router and the `nextjs/app` folder correspondingly. We need to update the README correspondingly.
=> (docs) Fixed the main frontend path in README

templates/extensions/foundry/packages/foundry/script/generateTsAbis.js
Fixes: https://github.com/scaffold-eth/scaffold-eth-2/issues/805
Sometimes (reproducible by me but not @technophile-04) the `yarn deploy` would error complaining about using an undefined property. This fixes that.
_Closes #805_
=> Fix #805 - Check property exists before using it

package.json, packages/nextjs/app/blockexplorer/address/[address]/page.tsx, packages/nextjs/app/blockexplorer/transaction/[txHash]/page.tsx, packages/nextjs/app/blockexplorer/transaction/_components/TransactionComp.tsx, packages/nextjs/next.config.js, packages/nextjs/utils/scaffold-eth/common.ts
An alternate solution to #824 (which doesn't require manual work) 
As the error mentioned in #785 : 
> Error: Page "/blockexplorer/transaction/[txHash]" is missing "generateStaticParams()" so it cannot be used with "output: export" config.
Therefore used [`generateStaticParams`](https://nextjs.org/docs/app/api-reference/functions/generate-static-params) from NextJs. 
```ts
export function generateStaticParams() {
return [{ address: "0x0000000000000000000000000000000000000000" }];
}
```
having the above code in blockexplorers `/[address]` & `/[txHash]`, when NextJs build the prod version it will generate 2 static dummy pages and won't fail. 
--- 
Does having  `generateStaticParams` break the blockexplorer when tinkering around on localnetwork ? 
No, since …
=> add generateStaticParams to blockexplorer address and txHash

packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
1. Moved `readEvents` to `useCallback`, so it's clear which dependencies it has
2. Since `fromBlock` is required prop, removed if's like `if (fromBlock)`
3. Combined two useEffects with the same functionality `readEvents();` and
```
if (!deployedContractLoading) {
readEvents();
}
```
The one without `if (!deployedContractLoading)` was buggy - on load it threw errors to the console 
4. Changed default state of events to `[]`, so we don't guess is it array or undefined
=> Update useScaffoldEventHistory hook

packages/nextjs/components/SwitchTheme.tsx, packages/nextjs/hooks/scaffold-eth/useScaffoldWriteContract.ts, packages/nextjs/utils/scaffold-eth/contract.ts
Fixes typo in types + removes redundant parentheses
=> fix: types typo

package.json
I have added 'engines' to the package.json file. This practice ensures consistency in the development environment, which is crucial when collaborating with colleagues who may have different versions of Node.js installed
Your ENS/address: wolfcito.eth
=> chore: adding engines fields in package.json to hint people

packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/AddressQRCodeModal.tsx
Fixes #835 
Feel free to close this PR if we should not handle issues on different fonts 🙌. Thought it would good to create because was happening in SRE challenges, but maybe not!
For address `0x04AAa2B551eaAb54568a5546be5d61407cA9D70c` is looking like this in Challeneges after fix:
=> Adjust QR Code modal spacing to fix copy icon size on bigger fonts

packages/nextjs/utils/scaffold-eth/contract.ts
Currently, types of arguments doesn't work as expected when contract has more that one event. Example:
if I just add `event SomeOtherEvent(string someString, uint256 someValue);` to `YourContract.sol`, I'm receiving this error when trying to work with logs from `useScaffoldWatchContractEvent`.
=> fix: useScaffoldWatchContractEvent logs args types

packages/nextjs/components/scaffold-eth/Faucet.tsx, packages/nextjs/components/scaffold-eth/FaucetButton.tsx, packages/nextjs/hooks/scaffold-eth/useTransactor.tsx
When trying to send raw transaction using `useTransactor` hook we get below type error :
=> update useTransaction parameters

packages/nextjs/package.json, yarn.lock
This was noticed by @carletex , that while playing around with the wagmi `useSendTranaaction` hook and burner wallet we get an error (since there was mistake in gas calculation checkout https://github.com/scaffold-eth/burner-connector/pull/16 for more details) 
To try the bug on `main` branch, copy paste this and try clicking send button  
<details>
<summary>
Test Code  : 
</summary>
```tsx
"use client";
import Link from "next/link";
import { parseEther } from "viem";
import { useAccount, useSendTransaction } from "wagmi";
import { BugAntIcon, MagnifyingGlassIcon } from "@heroicons/react/24/outline";
import { Address } from "~~/components/scaffold-eth";
import { useTransactor } from "~~/hooks/scaffold-eth";
const { …
```
=> update burner version

packages/nextjs/hooks/scaffold-eth/useDeployedContractInfo.ts, packages/nextjs/package.json, packages/nextjs/utils/scaffold-eth/getMetadata.ts, packages/nextjs/utils/scaffold-eth/getParsedError.ts, yarn.lock
Updated wagmi, viem, rainbowkit to their latest version.  
Wagmi and Viem have pushed some nice experimental freatures for playing around new EIP's in AA world 5792, 3074, 6492 checkout : 
- https://viem.sh/experimental
- https://wagmi.sh/react/api/hooks/useCallsStatus
And also in latest wagmi version, they updated coinbase connector so that coinbase smart wallets can be used checkout: https://x.com/wevm_dev/status/1791218863545126978
=> Bump wagmi, viem and rainbowkit versions

packages/nextjs/utils/scaffold-eth/getMetadata.ts
Fixes #850 
In order to get our default favicon back, we could follow different approaches (let me know if I missed a better approach!):
1. Add it explicitly to `getMetadata`.
2. Add it as optional prop with default value to `getMetadata`, similar to how we handling unfurl image with `imageRelativePath` prop.
3. Moving `favicon.png` from /public to /app and rename it to `icon.png` or change the format to `favicon.ico`. See [this](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons)
I went for 1 just because it felt simple, and if I had to change the favicon for my app, I'd probably search favicon/icon in the code. 
I don't have a strong opinion about this, would love to know what do you think the best practice would be. TYSM ♥
=> Add default favicon

packages/nextjs/components/Footer.tsx
Add zeros to native currency price when price is integer
Before:
After:
=> Add zeros to native currency price when price is integer

packages/nextjs/components/scaffold-eth/Balance.tsx
The `usdMode` flag wasn't working on our `Balance` component, since the price takes some time to load and we were always setting `displayUsdMode` to false on the first render (price > 0 condition)
You can test in `page.tsx` 
```tsx
/* This will always show the Balance in ETH mode, even if we say usdMode */
<Balance address={connectedAddress} usdMode /> 
```
This PR adds the missing `useEffect` (as in EtherInput).
=> Add use effect on Balance component for the price

funding.json
Adding a few repositories to our OP Retro Funding Round 4 submission. In order to verify, OP asks to add this json file at the root folder of the repo.
We are adding to our submission these repos:
I guess we'll be able to delete after the round. Hopefully in Round 7 (Dev Tooling) they can add other kind of verification.
=> Add OP Retro Funding round 4 verification

packages/nextjs/components/Footer.tsx, packages/nextjs/components/ScaffoldEthAppWithProviders.tsx, packages/nextjs/components/scaffold-eth/Balance.tsx, packages/nextjs/components/scaffold-eth/Input/EtherInput.tsx, packages/nextjs/hooks/scaffold-eth/index.ts, packages/nextjs/hooks/scaffold-eth/useDisplayUsdMode.ts, packages/nextjs/hooks/scaffold-eth/useInitializeNativeCurrencyPrice.ts, packages/nextjs/hooks/scaffold-eth/useNativeCurrencyPrice.ts, packages/nextjs/hooks/scaffold-eth/useTargetNetwork.ts, packages/nextjs/services/store/store.ts
Adds `useDisplayUsdMode` hook which helps to work with nativeCurrency/USD values.
Hook takes as parameter `defaultUsdMode` which sets an initial value, and returns `{ displayUsdMode, toggleDisplayUsdMode }`. `toggleDisplayUsdMode` allows to change inner `displayUsdMode`, and `displayUsdMode` basically returns current USD mode.
`defaultUsdMode` and `displayUsdMode` variables are booleans. `true` means `USD`, `false` means Native Currency.
See discussion [here](https://github.com/scaffold-eth/scaffold-eth-2/pull/856)
Note:
- I didn't set default state to `undefined` since with it we need additional conditions like `if (typeof nativeCurrencyPrice !== "undefined" && nativeCurrencyPrice > 0)` etc. 
- I assigned default `isFetching` value for price to `true`, so it's clear that if `!isFetching …
=> feat: useDisplayUsdMode hook

packages/nextjs/package.json, yarn.lock
We actually just updated wagmi, viem and rainbowkit last week in #849 
But in latest version rainbowkit now allows users to set `smartWallet` preferece for coinbase, checkout out [here](https://arc.net/l/quote/ajmwsize) 
Also in new wagmi version they have update coibasewalletsdk version. 
Having this both updated will also help people use latest version coinabsewalletsdk , especially to those who are participating in base hackathon
=> up wagmi viem rainbowkit

packages/nextjs/app/page.tsx, packages/nextjs/components/scaffold-eth/Address.tsx
Fixed the address components copy icon and `"connected address" + Address component` alignment for smaller screen size.
https://github.com/scaffold-eth/scaffold-eth-2/assets/78664749/51cbaf85-fe13-4500-8182-1d6503944d9d
_Closes #863_
Your ENS/address: 0xfC001B20Db6195b148cfc4F7685091931D93cD93
=> fix: address components copy icon on small screens

packages/nextjs/package.json, yarn.lock
Seems there is some problem in new typescript version, it not registering AddressType properly. So for now locked it's version. 
Also locked the version of abitype (just to be future proof, since we have also locked viem and wagmi version). 
Fixes #870 
Run on main branch and it fails : 
```shell
yarn vercel
```
Switch to this pr branch and run `yarn vercel` and it should work
=> lock typescript and abitype version

packages/nextjs/app/debug/_components/contract/utilsContract.tsx
When entering a large number into an `IntegerInput` component, it is parsed as a JSON string and loses precision.
For example, entering `85604566775863511922702956178915374775782418036268384638508224920020197708340` is parsed into `85604566775863516368369806302131844469805175632226226214501379502487210295296`.
This is fixed by first attempting to convert the `string` value to a `BigInt` and then returning that value if successful.
Your ENS/address: paulburke.eth
=> Fixes BigInt parsing losing precision in IntegerInput

packages/nextjs/package.json, packages/nextjs/tsconfig.json, packages/nextjs/types/abitype/abi.d.ts, yarn.lock
Change ts `moduleResolution` to `Bundler`
Context: https://github.com/scaffold-eth/create-eth/pull/74#discussion_r1675316747
Also added paths for abitype/viem/wagmi since with `Bundler` `abi.d.ts` is ignored
Note: Could you check is everything ok with types? My Vscode getting mad, it can show or not show errors for same code. (as you see build works fine)
=> feat: bundler module resolution

packages/nextjs/app/debug/_components/contract/utilsContract.tsx
Actually this was caused due to #893. 
When people try to enter address is converted to BigInt. 
https://github.com/user-attachments/assets/5cda53c3-8e16-4cdf-b5e1-c23cf70f1e03
=> fix: inputs parsing numbers instead of address

packages/foundry/script/00_deploy_your_contract.s.sol, packages/foundry/script/Deploy.s.sol
Separate your contract deploy script from so that we enforce people to follow a pattern. 
The reason we need to enforce this pattern is because `exportDeployments()` should be called only once and too after all the deployments are done. 
So basically `Deploy.s.sol` file is the main file which import different deploy script of different contracts and in the end it calls the `exportDeployments()` which creates all the necessary files for generateTsAbi.js fucntion. 
Checkout second part of this for more details : https://github.com/scaffold-eth/scaffold-eth-2/pull/781#issuecomment-2018642266
CC @jrcarlos2000 feel free suggest some cleanups / better practices in foundry. 
- Kindof similar patter followed in this twitter thread https://x.com/jj_ranalli/status/1656384664020434949
- Foundry …
=> foundry: separate out your contract deployments

packages/nextjs/components/scaffold-eth/ProgressBar.tsx
-> Modifies the nprogress bar so that it only forks for non external links.
-> Implements the changes from:
https://github.com/BuidlGuidl/extensions-hackathon/pull/23#event-13881221641
https://github.com/user-attachments/assets/0f191f3c-b02b-4782-981c-89192d958b21
Fixes #908 
=> Exclude external links from triggering progress bar

packages/nextjs/hooks/scaffold-eth/useTransactor.tsx
https://www.loom.com/share/2727672272374fbba1c4afcc33b8d9a3?sid=d22eb180-f1de-4629-8256-413802920376
- The `useTransactor` hook displays a success notification even if the transaction reverts, which is confusing for users.
- When using tanstack's `useMutation`, the `onSuccess` will trigger even when the tx reverts 
- Only show success notification when tx receipt status is success
- Throw a "Transaction reverted" error if tx receipt status is not `"success"` 
- so that `useMutation`'s `onError` is triggered 
- so that user sees a "Transaction reverted" notification
- so developer that is relying on transaction successfully executing doesnt get wrecked :melting_face: 
- https://use-transactor-example.vercel.app/
- https://github.com/MattPereira/scaffold-eth-2/tree/tx-revert-example
=> Handle tx revert in `useTransactor`

packages/nextjs/hooks/scaffold-eth/useTransactor.tsx
I think its nice UX to point to user to block explorer when transaction receipt is reverted. Viem does not give us the actual reason for transaction receipt revert as mentioned [here](https://github.com/wevm/viem/issues/1767#issuecomment-1925986197) they only give you status "reverted". So maybe its nice idea to point to block explorer for actual reason. 
To test you could checkout: 
```shel
git switch tx-revert-example
```
Checkout home page on how to make transaction revert or you could checkout Matt's video [here](https://www.loom.com/share/2727672272374fbba1c4afcc33b8d9a3?sid=d22eb180-f1de-4629-8256-413802920376). I have just bought Matt's example branch here and updated `useTransactor` with this branch code. 
<details>
<summary>
Demo video : 
</summary> …
=> show blockexplorer link when transaction receipt is reverted

packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
Fixes useScaffoldEventHistory caching
Fixes #903
=> fix: useScaffoldEventHistory caching

packages/hardhat/tsconfig.json
This allows importing json in `.ts` files for example in scripts. 
to test : 
```shell
cd packages/hardhat
```
```shell
echo '{"test": "value"}' > scripts/test.json
```
then create a new file in `scripts/test.ts` and try importing it: 
```ts
import test from "./test.json";
console.log(test);
```
^ on main branch above should give you ts error: 
"Cannot find module './test.json'. Consider using '--resolveJsonModule' to import module with '.json' extension. [2732]"
But on this branch it should work. 
Also to see if script runs at runtime properly make sure you are `cd packages/hardhat` and then run :
```shell
yarn hardhat run scripts/test.ts
```
=> allow json module imports

packages/nextjs/app/debug/_components/DebugContracts.tsx, packages/nextjs/utils/scaffold-eth/contractsData.ts
Fixes debug page in case where the app uses different contracts on different chains
Before:
https://github.com/user-attachments/assets/b68a96d9-25cd-4c8e-b473-3964a8146377
After:
https://github.com/user-attachments/assets/47e5f585-b9e4-4288-8d7b-7810fa4c513a
=> fix: debug page for different contracts on different chains

packages/nextjs/components/scaffold-eth/Input/AddressInput.tsx
There is a bug in the AddressInput component that shows when changing the value from the outside without triggering `onChange`.
To test:
1. Enter `atg.eth` => it resolves and shows the blockie, ensName, and avatar
2. Click the Change address button. Everything works except the ensName which remains the same.
```tsx
"use client";
import { useState } from "react";
import { useAccount } from "wagmi";
import { AddressInput } from "~~/components/scaffold-eth";
const [inputAddress, setInputAddress] = useState("");
return (
<>
<div className="flex items-center flex-col flex-grow pt-10 gap-2">
<AddressInput value={inputAddress} onChange={setInputAddress} />
<button
className="btn btn-primary"
onClick={() => …
```
=> Reset enteredEns on Address input when changing the value

README.md
Updated the README to mention some details about keystore accounts so people using it will get a gist. 
Added "Deploying to live networks" but in future we should delete this section from here and update `docs.scaffoldeth.io` with it.
=> update README with keystore details

packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/AddressInfoDropdown.tsx, packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/AddressQRCodeModal.tsx, packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/NetworkOptions.tsx, packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/WrongNetworkDropdown.tsx, packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/index.tsx, packages/nextjs/components/ui/button.tsx, packages/nextjs/components/ui/dialog.tsx, packages/nextjs/components/ui/dropdown-menu.tsx, packages/nextjs/package.json, packages/nextjs/tailwind.config.js, yarn.lock
Custom rainbowkit button + dropdown implemented with shadcn
See https://github.com/scaffold-eth/scaffold-eth-2/pull/937#discussion_r1760213449 and https://github.com/scaffold-eth/scaffold-eth-2/pull/937#discussion_r1760199979 first
Buttons functionality
https://github.com/user-attachments/assets/7d0ba4f7-7508-46c0-8b5f-ccc67f7000f2
---
With networks switch
https://github.com/user-attachments/assets/4d8693e2-df21-49b0-896e-3e270bea4c4e
---
Wrong network dropdown
https://github.com/user-attachments/assets/77ec7cb6-0074-40ee-ab7a-869b1a1aa74d
---
Dark theme
https://github.com/user-attachments/assets/2fd32a10-eb2f-4d4c-b8d5-8376eb83feeb
=> Shadcn rainbowkit button + dropdown

packages/hardhat/package.json, yarn.lock
Update major version of `envfile`
Part of point 5 https://github.com/scaffold-eth/scaffold-eth-2/pull/917#issuecomment-2320138630
=> Update envfile lib

packages/nextjs/app/debug/_components/DebugContracts.tsx
Fixes https://github.com/scaffold-eth/scaffold-eth-2/issues/939
One of the possible (and simple) solutions is to use sessionStorage instead of localStorage. As I understand it doesn't change anything except one case: 
User worked with debug page where he chose some non-first contract. User closes browser tab with his debug page and open debug page in another browser tab. With localStorage, last chosen contract will be selected. With sessionStorage first contract will be selected. I believe it's not a problem at all
Additionally, using sessionStorage adds possibility to view different contracts of debug page in different browser tabs
----
What I also tried to do:
- use simple hash function depending on contractNames
```
const [selectedContract, setSelectedContract] = …
```
=> Fix debug page contracts view

packages/hardhat/.env.example, packages/hardhat/hardhat.config.ts, packages/nextjs/scaffold.config.ts, packages/nextjs/services/web3/wagmiConfig.tsx
- We set the alchemy key for hardhat for deployments
- For frontend we use it as a fallback if public rpc fails
=> add alchemy key as fallback

packages/nextjs/components/scaffold-eth/Address/AddressCopyIcon.tsx, packages/nextjs/components/scaffold-eth/Balance.tsx, packages/nextjs/components/scaffold-eth/Input/Bytes32Input.tsx, packages/nextjs/components/scaffold-eth/Input/BytesInput.tsx, packages/nextjs/components/scaffold-eth/Input/EtherInput.tsx, packages/nextjs/components/scaffold-eth/Input/IntegerInput.tsx
Fixes #990 
To test copy this to `/nextjs/app/page.tsx`. Before the changes button of every component inside the form submitted it. Form is inside the borders
<details><summary>Code</summary>
<p>
```
"use client";
import { useState } from "react";
import Link from "next/link";
import { useAccount } from "wagmi";
import { BugAntIcon, MagnifyingGlassIcon } from "@heroicons/react/24/outline";
import { Address, Balance, EtherInput, IntegerInput } from "~~/components/scaffold-eth";
const { address: connectedAddress } = useAccount();
const [value, setValue] = useState("");
return (
<>
<div className="flex items-center flex-col flex-grow pt-10">
<div className="px-5">
<h1 className="text-center">
<span className="block text-2xl …
```
=> fix: form submitting

packages/nextjs/utils/scaffold-eth/decodeTxData.ts
Instead of logging errors for expected behavior it adds 'Unknown ABI' to function name.
Before
After
_Closes #984_
Your ENS/address: harmont.eth
=> fix: removed unecessary logs for decoding tx in block-explorer

packages/nextjs/app/blockexplorer/_components/PaginationButton.tsx, packages/nextjs/app/blockexplorer/_components/SearchBar.tsx, packages/nextjs/app/blockexplorer/_components/TransactionHash.tsx, packages/nextjs/app/debug/_components/contract/DisplayVariable.tsx, packages/nextjs/app/debug/_components/contract/TxReceipt.tsx, packages/nextjs/app/debug/_components/contract/utilsDisplay.tsx, packages/nextjs/components/SwitchTheme.tsx, packages/nextjs/components/scaffold-eth/Address/Address.tsx, packages/nextjs/components/scaffold-eth/Balance.tsx, packages/nextjs/components/scaffold-eth/Input/InputBase.tsx
Removed hardcoded colors so colors will be better for extensions.
Changes:
general:
- copy button near address and transactions is the same color as default text
- changed input content and placeholder colors
- switch theme toggle color is now `text-base-content`, so it has the same color as switch icon, has better contrast and also is better for extensions, for example sre-challenges light theme
- changed balance error border color
- changed receipt object keys colors
debug page:
- display variable is now `text-base-content/80` and also normal font-weight so it has better contrast with var title
blockexplorer:
- changed color of searchbar placeholder
- changed hardcoded color of pagination button to `btn-disabled`
=> Remove hardcoded colors

README.md
As we discussed yesterday, we are moving away from SE-2 clone method. The first step is to remove it from the docs / READMEs / etc.
Related https://github.com/scaffold-eth/scaffoldeth.io/pull/41
=> Remove clone command + add npx install

packages/hardhat/.prettierrc.json, packages/hardhat/contracts/YourContract.sol, packages/hardhat/package.json, yarn.lock
This discussion was born while working on CTF, Thanks to @carletex for pointing it out. 
Solidity formatting was not handled properly and now we follow https://docs.soliditylang.org/en/latest/style-guide.html 
Also another reason to create this PR was add this in `hardhat/package.json`: 
```json
"format": "prettier --write './**/*.(ts|sol)'",
```
This compliments https://github.com/scaffold-eth/create-eth/pull/158#issuecomment-2495432683
=> fix solidity formatting

packages/hardhat/hardhat.config.ts, packages/hardhat/scripts/generateTsAbis.ts
This is something which we did at CTF repo. Doing this no more requires `99_deployScript` to be present and also avoids the problem people deleting it by mistake
=> move 99_deployScript as hardhat task

packages/nextjs/package.json, yarn.lock
Copying behaviors from #998 
deployment log from `main` branch
```
...
Running "vercel build"
Vercel CLI 39.1.1
Running "install" command: `yarn install`...
yarn install v1.22.19
info No lockfile found.
...
```
So our `yarn.lock` file is ignored and the last version will be installed when we have `^x.y.z` versions of packages. It can cause errors
yarn version `3.2.3` should be used
`yarn.lock` should be used
----
Since our `yarn.lock` is located at the root of the repo, I think we can't use locked versions of nextjs package on our deploys. But it's possible at least to change yarn version to `3.2.3` from `^1`. I'm still not sure if it adds a lot of value but I think it could solve some issues we had before when using yarn v1 or other incompatible yarn versions.
So, to use current version …
=> Use current yarn version on deploy to vercel

packages/nextjs/package.json, packages/nextjs/scaffold.config.ts, packages/nextjs/services/web3/wagmiConfig.tsx, yarn.lock
I am not sure what's the best solution for this is, but realized that public RPC URL's are not reliable. Especially recognized this with sepolia public rpc url which wagmi has `https://rpc2.sepolia.org`. 
It seems to read the wrong state example balance and also not able to fetch read variables. 
<details>
<summary>
Demo video:     
</summary>
https://github.com/user-attachments/assets/05f787a6-3ad2-4047-85eb-9359187b080a
</details>
1. Switch to main branch.
2. Copy this inside `externalContracts.ts`
<details>
<summary>
externalContracts.ts
</summary>
```ts
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";
/**
* @example
* const externalContracts = {
*   1: {
*     DAI: {
*       address: "0x...",
*       abi: [...],
*     },
*   },
* } as const;
*/
const …
```
=> reverse rpc fallback order

packages/nextjs/package.json
Context: https://github.com/scaffold-eth/se-2-challenges/pull/245#pullrequestreview-2503416298
I think we need to disable telemetry by default, because
- vercel cli asks to do additional actions to approve telemetry before deploy
- I am not sure people want to vercel to collect their data
Vercel telemetry [docs](https://vercel.com/docs/cli/about-telemetry)
=> Disable vercel telemetry

packages/nextjs/hooks/scaffold-eth/useDeployedContractInfo.ts, packages/nextjs/hooks/scaffold-eth/useScaffoldWriteContract.ts
This allows developers to consume `useScaffoldWriteContract` and `useDeployedContractInfo` hook in both ways until we make breaking changes release : 
Example of `useScaffoldWriteContract`
Old: 
```ts
const { writeContractAsync: depeRecatedWriteAsync } = useScaffoldWriteContract("YourContract");
```
When using the Old way the IDE should give the warning : 
New: 
```ts
const { writeContractAsync: newWriteAsync } = useScaffoldWriteContract({
contractName: "YourContract",
chainId: 31337,
});
```
<details>
<summary>
Copy this in page.tsx
</summary>
```tsx
"use client";
import { useAccount } from "wagmi";
import { Address } from "~~/components/scaffold-eth";
import { useDeployedContractInfo, useScaffoldReadContract, useScaffoldWriteContract } from …
```
=> make `useScaffoldWriteContract` & `useDeployedContractInfo` backward compatible

packages/nextjs/hooks/scaffold-eth/useDeployedContractInfo.ts, packages/nextjs/hooks/scaffold-eth/useScaffoldWriteContract.ts
Without this we show warnings on every render so all the console is yellow, try example from https://github.com/scaffold-eth/scaffold-eth-2/pull/1015
=> Move warnings to useEffect

packages/nextjs/package.json, yarn.lock
This version allows the generation for a new burner wallet for each browser tab using a sessionStorage as option.
add this line to `wagmiConnectors.ts` to use sessionStroage version and test: 
```ts
rainbowkitBurnerWallet.useSessionStorage = true;
```
For more details checkout README https://github.com/scaffold-eth/burner-connector
OG PR: https://github.com/scaffold-eth/burner-connector/pull/24
=> up burner-connector version

packages/nextjs/app/debug/_components/DebugContracts.tsx
This sorts in natural number order. 
In main branch: Contract1, Contract11 and then Contract2 will appear in debug page
We implemented this logic in https://github.com/BuidlGuidl/ctf.buidlguidl.com/blob/e5f418f7bd1ac942f99f49e689101c53ae6b5f78/packages/nextjs/app/debug/_components/DebugContracts.tsx#L12-L14
1. Create this files: 
<details>
<summary>
Contract1.sol
</summary>
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;
contract Contract1 {
// State variable
uint256 public counter;
// Event declaration
event CounterIncremented(uint256 newValue);
event CounterReset();
// Increment the counter
function increment() public {
counter += 1;
emit CounterIncremented(counter);
}
// Get the current counter value
function getCounter() public view returns (uint256) {
return …
```
=> update contract sort order in numberic way

packages/nextjs/package.json, yarn.lock
Lowered the wagmi nd viem version. Because in latest wagmi/viem versions they stopped simulating the contract write function before giving wallet pop up. 
I'm not sure if it was intended by them or by mistake. Created a detailed issue https://github.com/wevm/wagmi/issues/4516
But for now lowered the wagmi nd viem version until they answer or fix it in latest version 
This also will remove the blocker from this issue: https://github.com/BuidlGuidl/ctf.buidlguidl.com/issues/7
Maybe we can release the create-eth latest version helpful for ctf after we merge this 🙌
Add this in `externalContracts.ts`and switch to sepolia. 
<details>
<summary>
externalContracts.ts
</summary>
```ts
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";
/**
* @example
* const …
```
=> downgrade wagmi and viem version

package.json
Solved error on using old nextjs:lint by next:lint command
_Failing when running `yarn lint` due to using `yarn nextjs:lint` old command. We must use `yarn next:lint` one._
_Closes #{1040}_
Your ENS/address: meketom.eth
=> Error on yarn lint command

packages/nextjs/components/Header.tsx
While testing the [BG RPC](https://client.buidlguidl.com/) I did a SE-2 build where I wanted to remove all the "automatic" RPC calls and only trigger them when doing an action (e.g. clicking a button).
After deleting all the obvious (getting the ETH price, the Balance from the connected wallet, etc) I realized that a RPC call for getting the connected address balance was still happening. 
Digging a bit, this was coming from the `FaucetButton` component: even if the component doesn't show (it returns `null` if not in localhost) the `useWatchBalance` hook is still being called.
This PR adds a check so we don't render/execute the FaucetButton at all (following the same logic as the block explorer link in the footer)
You can test by pulling down …
=> Remove  unnecessary RPC call on Faucet Button

packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts, packages/nextjs/hooks/scaffold-eth/useScaffoldWatchContractEvent.ts
Remove indexed events arguments for named event arguments
Updated Challenge 1 readme since it already has type errors if arguments are named https://github.com/scaffold-eth/se-2-challenges/commit/19b1c29c912f888796e64cff931c23772d9363f2
I think we don't need to update Se-2 docs for now since looks like not using indexed params is expected behavior
Fixes #1045
=> Remove indexed event params

packages/nextjs/app/debug/_components/contract/WriteOnlyFunctionForm.tsx, packages/nextjs/hooks/scaffold-eth/useScaffoldWriteContract.ts, packages/nextjs/package.json, packages/nextjs/utils/scaffold-eth/common.ts, packages/nextjs/utils/scaffold-eth/contract.ts, yarn.lock
Upgraded wagmi, viem, rainbowkit to latest version. 
Since wagmi/viem now by default removed the simulation of contract write we have to handle it now, check out https://github.com/wevm/wagmi/issues/4516
Initially, I thought I would add simulation logic to `useTransactor` but it seems there is no simulation hook / util for normal transaction in wagmi/viem and its only available for contract interaction.  So it made sense to add the logic in `useScaffoldWriteContract` itself. 
Also added a new option to `useScaffoldWriteContract` and `disbaleSimulate` if anyone wants to disable simulation. 
Please feel free to be nitpicky on naming / approach! 
--- 
<details>
<summary>
Replace this in `externalContracts.ts`
</summary>
```ts
import { GenericContractsDeclaration } from …
```
=> Up wagmi, viem and rainbowkit

packages/nextjs/scaffold.config.ts, packages/nextjs/services/web3/wagmiConfig.tsx, packages/nextjs/utils/scaffold-eth/networks.ts
Currently, changing the RPCs for the frontend is a bit tricky since SE-2 assumes that you are going to use Alchemy, and tweaking it requires you to tweak `wagmiConfig` and it's not very extract forward (we area  bit vendor-locked with Alchemy)
Let the builders define the `rpcOverrides` in `scaffold.config.ts`. We don't want to pollute the config file, but RPC config seems like a top-level kind of config.
Tried to come up with the simplest way that respect the current functionality.
Really open!!
- Should we do this?
- Naming
- Logic
=> RPC Overrides

packages/nextjs/hooks/scaffold-eth/useTransactor.tsx
Creating production build using `npm run build` causes build errors:
- Reference of `getPublicClient` should be changed from import `@wagmi/core` to `wagmi/actions`
- Also fixes the issue `publicClient` is possibly undefined in:
```ts
//useTransactor.tsx
//`publicClient` is possibly undefined
transactionReceipt = await publicClient.waitForTransactionReceipt({
hash: transactionHash,
confirmations: options?.blockConfirmations,
});
notification.remove(notificationId);
```
`0xBa9Da840bA7B5d0F227716f2e7266675cE697e9D`
=> fix: import on wagmi package

packages/nextjs/app/page.tsx
The layout wasn't working as expected due to incorrect flex-col/flex-row setup, especially on different screen sizes. The proposed changes provide a clean layout for all screen sizes.
Tailwind follows a mobile-first approach, meanwhile the SE-2 homepage seemed to have been following a desktop-first approach: https://tailwindcss.com/docs/responsive-design#working-mobile-first which led to unexpected behaviour.
Because of this, the example: `flex-col sm:flex-row` does not work as expected. On small screens, it actually defaults to `flex-col`. Since when tailwind sees `flex-col`, it actually interprets it as `sm:flex-col`.
The `Connected Addresses` section now simply is a `flex-col`, since with the (now removed) `sm:flex-row`, mobile screens would have content displaying horizontally …
=> Small fixes to homepage layout

packages/hardhat/hardhat.config.ts
Hello fellow builders! 👋 This PR gives our network configuration a much-needed refresh, saying goodbye to deprecated networks and welcoming their shiny new replacements.
- 🔴 **Removed Deprecated Networks**:
- Bid farewell to Polygon Mumbai (it served us well, RIP 🪦)
- PGN and PGN Testnet have left the chat (they've gone to the great blockchain in the sky ☁️)
- 🟢 **Added New Networks**:
- Welcomed Polygon Amoy as Mumbai's successor (the torch has been passed! 🔥)
- Introduced Polygon zkEVM Cardona as the replacement for the previous zkEVM testnet
- 🛠️ **Updated Configuration**:
- Updated RPC endpoints to point to the new networks
- Kept all account configurations consistent
Both new networks have been thoroughly tested:
- `yarn deploy --network polygonAmoy` ✓
- `yarn deploy --network …
=> 🚀 Network Updates: Out with the Old, In with the New!

packages/foundry/scripts-js/selectOrCreateKeystore.js
When the user has no keystores yet, the `yarn deploy --network network_name` just fails.
This PR prevents that by showing the users the menu instead of giving the user an error message. 
I think we can definitely improve this but this should be a good start!
Before:
After:
Fixes #1072
=> Forward user to creating a keystore if none exist

packages/nextjs/hooks/scaffold-eth/useNetworkColor.ts, packages/nextjs/hooks/scaffold-eth/useSelectedNetwork.ts, packages/nextjs/hooks/scaffold-eth/useTargetNetwork.ts, packages/nextjs/services/store/store.ts
Adds chain metadata to  `useSelectedNetwork` response, so other hooks like `useNetworkColor` have the color metadata from the chain to work as intended.
_Closes #1092
=> Add chain metadata to `useSelectedNetwork` hook

packages/nextjs/app/blockexplorer/_components/AddressComponent.tsx, packages/nextjs/app/blockexplorer/_components/ContractTabs.tsx, packages/nextjs/app/blockexplorer/address/[address]/page.tsx
Remove hardcoding for `address: string` and instead use `Address` type from viem so that if users switches: 
```ts
// abi.d.ts
type AddressType = string;
```
=> remove hardcoded string and use AddressType

packages/nextjs/app/debug/_components/contract/WriteOnlyFunctionForm.tsx, packages/nextjs/hooks/scaffold-eth/useScaffoldWriteContract.ts, packages/nextjs/hooks/scaffold-eth/useTransactor.tsx, packages/nextjs/utils/scaffold-eth/contract.ts
See the bug and how to reproduce in #1145 
It can't parse the error because it checks only abi of the ContractA. This PR fixes it, now when trying to find error it parses abi's of all the deployed contracts.
Error after fix
Fixes #1145
=> Fix contract interactions error

packages/hardhat/scripts/generateTsAbis.ts
How to reproduce:
1. Deploy your contract to any chain except localhost. Let's assume the chain is sepolia. During deployment new folder will be created: `packages/hardhat/deployments/sepolia`. The folder includes ` .chainId`, `*.json` files and `solcInputs` folder
2. Switch to some other branch. Files from `packages/hardhat/deployments/sepolia` folder will disappear but folder still exist
3. Run `yarn deploy` from new branch. `generateTsAbi.ts` script will try to find `.chainId` file inside the folder and fail, which cause the error, something like this
<details><summary>Error</summary>
<p>
```
$ yarn deploy
Generating typings for: 1 artifacts in dir: typechain-types for target: ethers-v6
Successfully generated 34 typings!
Compiled 1 Solidity file successfully (evm target: paris). …
```
=> Fix deployments chainId error

packages/nextjs/app/debug/_components/contract/InheritanceTooltip.tsx
- Changed md:break-normal to md:break-words
- Fixes tooltip overflow for long contract names"
_Closes #1159 _
Your ENS/address: 0x56596b38790E1D385DA9376C54647604f878acBb
=> fix: prevent text overflow in inheritance tooltip

packages/hardhat/hardhat.config.ts, packages/nextjs/utils/scaffold-eth/networks.ts
Celo Alfajores Testnet will sunset on the 30th of September, aligned with Holseky. Celo Sepolia was officially announced on the 13th of August 2025. 
_Closes #{issue number}_
=> Update Celo Testnet from Celo Alfajores to Celo Sepolia 

README.md, packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
Addresses issue #1166 by adding documentation warnings about using `useScaffoldEventHistory` in production.
- ✅ Added JSDoc deprecation warning to the hook
- ✅ Updated documentation to warn about RPC limitations
- ✅ Recommended indexer solutions for production use
The hook uses `getLogs` which can burn through RPC limits, especially on L2s with short block times. This change helps developers make informed decisions about when to use this hook.
Closes #1166
=> docs: add production usage warning for useScaffoldEventHistory
