- packages/frontend/components/scaffold-eth/Contract/ContractUI.tsx
- packages/frontend/components/scaffold-eth/Contract/utilsContract.tsx
Add loaded flag to getContractMethods on utilsContract to allow to check if the contract was loaded.
Now when there aren't any read or write method, the UI show a clear message.
> Add loaded flag to getContractMethods

- packages/nextjs/components/Footer.tsx
- packages/nextjs/components/Header.tsx
- packages/nextjs/pages/_app.tsx
- packages/nextjs/pages/index.tsx
- packages/nextjs/services/store/slices/ethPriceSlice.ts
- packages/nextjs/tailwind.config.js
Fixes #63 
Few other things tackled in this PR:
- Fix issue setting the Zustand state (for eth price)
- Created sticky footer
- Narrow the navbar
> Eth price footer

- packages/nextjs/package.json
- packages/nextjs/pages/_app.tsx
- yarn.lock
Using https://www.npmjs.com/package/nextjs-progressbar
I leave the default behavior. We can change the config later if we want.
closes #62
> Add Next.js Progressbar

- packages/nextjs/components/scaffold-eth/AddressInput.tsx
- packages/nextjs/components/scaffold-eth/Balance.tsx
- packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx
- packages/nextjs/components/scaffold-eth/Contract/DisplayVariables.tsx
- packages/nextjs/components/scaffold-eth/Contract/InputUI.tsx
- packages/nextjs/components/scaffold-eth/Contract/ReadOnlyFunctionForm.tsx
- packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx
- packages/nextjs/components/scaffold-eth/Contract/utilsComponents.tsx
- packages/nextjs/components/scaffold-eth/Contract/utilsDisplay.tsx
- packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx
- packages/nextjs/utils/scaffold-eth/networks.ts
- packages/nextjs/utils/scaffold-eth/toast.tsx
Previously the /debug was not compatible with dark mode and the UI was looking bad, tried fixing the color's also now utilizing colors from theme so they change dynamically.
Demo : 
https://user-images.githubusercontent.com/80153681/210276184-29a6f980-7701-46f2-a8c5-c34c8f98c0fa.mov
> Fix /debug page dark mode

- packages/hardhat/contracts/YourContract.sol
- packages/hardhat/deploy/00_deploy_your_contract.ts
- packages/nextjs/components/scaffold-eth/Balance.tsx
- packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx
> Basic draft for v2 of Purpose contract

- packages/nextjs/components/scaffold-eth/Contract/ReadOnlyFunctionForm.tsx
- packages/nextjs/components/scaffold-eth/Contract/TxReceipt.tsx
- packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx
- packages/nextjs/components/scaffold-eth/Contract/utilsDisplay.tsx
Collapsible Tx Receipt display:
https://github.com/scaffold-eth/se-2/issues/89#issue-1522385357
> i#89: Transaction receipts display on Write Functions

- packages/nextjs/components/scaffold-eth/Faucet.tsx
before:
https://user-images.githubusercontent.com/25638585/213171302-fe3397e2-8398-4bc3-8667-99a982fac9a4.mov
after:
https://user-images.githubusercontent.com/25638585/213171037-1650423d-e512-4be3-872b-1d76e8fd28eb.mov
> fix: remove faucet button jump

- packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx
- packages/nextjs/components/scaffold-eth/Contract/utilsComponents.tsx
updated tx value input, so now it works correctly with big numbers. Shows an "Invalid number" error message if the input isn't correct.
before:
https://user-images.githubusercontent.com/25638585/213478844-5b52f1d8-2baf-429f-8f3b-95c86324c833.mov
after:
https://user-images.githubusercontent.com/25638585/213479173-dad94ba4-4555-485f-af20-433de5cd2f7c.mov
> fix: tx value input

- packages/hardhat/contracts/YourContract.sol
Hey!
We were discussing with Carlos to add the comments in the code for the best developer experience as mentioned in issue https://github.com/scaffold-eth/se-2/issues/91. You can see my comments for the smart contract. 
Please lmk what you think. Happy to make the necessary changes if its over or under commented.
> Add comments to YourContract.sol

- packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx
- packages/nextjs/components/scaffold-eth/Contract/utilsComponents.tsx
https://user-images.githubusercontent.com/80153681/214339549-c313aaa1-8baa-4119-8834-399f5a58ba6f.mov
Fixes #108
> Fix bug for collapsible of writeFunction

- packages/hardhat/.env.example
- packages/hardhat/deploy/00_deploy_your_contract.ts
- packages/hardhat/hardhat.config.ts
Please refer to https://github.com/scaffold-eth/se-2/issues/91
> Add comments to Hardhat Files 

- packages/nextjs/components/scaffold-eth/AddressInput.tsx
> Show ENS avatar on address input

- packages/nextjs/components/ExampleUi/ContractData/index.tsx
- packages/nextjs/components/ExampleUi/ContractInteraction/PurposeSetter.tsx
- packages/nextjs/components/ExampleUi/ContractInteraction/UiDescription.tsx
- packages/nextjs/components/ExampleUi/ContractInteraction/index.tsx
- packages/nextjs/components/Footer.tsx
- packages/nextjs/components/Header.tsx
- packages/nextjs/pages/example-ui.tsx
before:
https://user-images.githubusercontent.com/25638585/215822628-e33baeaf-cae2-43a9-852d-1a8e18428738.mov
after:
https://user-images.githubusercontent.com/25638585/215821980-c66d07d0-4c63-41b1-8c68-5ceb41e42074.mov
> Feat/responsive example UI

- README.md
- package.json
- packages/nextjs/.env.production
- packages/nextjs/package.json
- yarn.lock
1. You run `yarn vercel`
Once you run `yarn vercel` it tells you to login with either of the below approaches (please ignore the command `yarn next:deploy` the ss is of before chaining the name) . 
**IMP** ->  The flow of login : 
1. Continue with Github 
Its like an OAuth authentication. if you select this option it will tell you to authorzie `vercel` on your github and once you accept it the CLI will automatically take you to next step. If you have already authorized to vercel on github only a vercel window pops up saying verified. 
2. Continue with email 
If you enter an email that is not registered with vercel it tells you to first signup with vercel 
2. After login you get to choose some options and add project name(this all can skipped with …
> deploy nextjs using vercel cli

- packages/nextjs/components/scaffold-eth/BlockieAvatar.tsx
- packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx
- packages/nextjs/components/scaffold-eth/index.tsx
- packages/nextjs/pages/_app.tsx
> Blockie avatar for Rainbowkit

- packages/nextjs/components/scaffold-eth/EtherInput.tsx
- packages/nextjs/components/scaffold-eth/index.tsx
https://user-images.githubusercontent.com/2486142/218287647-26963831-9306-418e-8cd1-e7d3bf40b45b.mp4
> EtherInput component

- packages/nextjs/components/Footer.tsx
- packages/nextjs/components/Header.tsx
- packages/nextjs/components/scaffold-eth/AddressInput.tsx
- packages/nextjs/components/scaffold-eth/EtherInput.tsx
- packages/nextjs/components/scaffold-eth/Faucet.tsx
- packages/nextjs/components/scaffold-eth/FaucetButton.tsx
- packages/nextjs/components/scaffold-eth/index.tsx
Created up a bare minimum faucet modal(The modal also closes if you click outside it, forgot to mention in demo) : 
https://user-images.githubusercontent.com/80153681/218315141-e7556c06-9c10-484e-9617-f9f61faf5edd.mov
TODO : 
Currently, the above 3 options are remaining, was wondering if I should conquer them in this PR itself?
> Create local faucet

- packages/nextjs/components/scaffold-eth/Contract/DisplayVariables.tsx
- packages/nextjs/components/scaffold-eth/Contract/ReadOnlyFunctionForm.tsx
- packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx
- packages/nextjs/components/scaffold-eth/Faucet.tsx
- packages/nextjs/hooks/scaffold-eth/useScaffoldContractWrite.ts
- packages/nextjs/hooks/scaffold-eth/useTransactor.tsx
- packages/nextjs/utils/scaffold-eth/index.ts
- packages/nextjs/utils/scaffold-eth/notification.tsx
renamed `toast` to the notification as discussed in #138
I ran `yarn next:lint` to check if anything broke and everything seems to work fine also tested manually
Fixes #138
> rename toast to notification

- packages/nextjs/components/scaffold-eth/AddressInput.tsx
- packages/nextjs/components/scaffold-eth/Contract/ReadOnlyFunctionForm.tsx
https://user-images.githubusercontent.com/25638585/218752772-15712487-14e4-477a-8093-5ddd2dd16264.mov
> feat: address => ens

- packages/nextjs/components/ExampleUi/ContractData.tsx
- packages/nextjs/components/scaffold-eth/Contract/DisplayVariables.tsx
- packages/nextjs/hooks/scaffold-eth/useAnimationConfig.ts
- packages/nextjs/tailwind.config.js
Added animation hook + basic animations
https://user-images.githubusercontent.com/25638585/218795086-4e30ef09-64f0-4803-be78-7e4c1e2cc80c.mov
> feat: contract changes feedback

- packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx
- packages/nextjs/pages/debug.tsx
🙇‍♂️ i deleted the network and fluff text and moved the static display to the left of the contract
> this looks better to me but I submit it for sand garden review

- packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx
- packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx
- packages/nextjs/hooks/scaffold-eth/index.ts
- packages/nextjs/hooks/scaffold-eth/useNetworkColor.ts
- packages/nextjs/utils/scaffold-eth/networks.ts
- packages/nextjs/utils/scaffold-eth/useNetworkColor.ts
Refactor mentioned here https://github.com/scaffold-eth/se-2/pull/182#issue-1589860816
> Refactor connect button network

- packages/nextjs/components/Footer.tsx
- packages/nextjs/components/SwitchTheme.tsx
This adds a background to the fixed footer elements, but only on mobile. #123
> fix(footer): align left footer buttons with right theme switcher

- packages/nextjs/next.config.js
This feels lot better and minimal 
Originally suggested here -> https://github.com/scaffold-eth/se-2/pull/195#discussion_r1112993857
> use direct === for ignoreError instead of ternary

- packages/nextjs/components/scaffold-eth/Contract/InputUI.tsx
- packages/nextjs/components/scaffold-eth/Contract/utilsDisplay.tsx
> fix(form): improved conversion buttons

- packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx
When it is connected to other networks
when it is connected to mainnet
> wrong network display + switch

- packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx
- packages/nextjs/hooks/scaffold-eth/useDeployedContractNames.ts
- packages/nextjs/pages/debug.tsx
- packages/nextjs/tailwind.config.js
> Add UI for displaying multiple contracts

- packages/nextjs/components/scaffold-eth/Contract/InputUI.tsx
- packages/nextjs/components/scaffold-eth/Contract/utilsComponents.tsx
- packages/nextjs/components/scaffold-eth/Contract/utilsDisplay.tsx
> fix: allow only numerical input for uint256 field

- packages/hardhat/hardhat.config.ts
- packages/hardhat/package.json
- yarn.lock
Alchemy now supports sepolia
https://www.alchemy.com/overviews/sepolia-testnet
> feat: sepolia alchemy rpc url

- packages/nextjs/hooks/scaffold-eth/useTransactor.tsx
> better transaction message again

- packages/nextjs/components/SwitchTheme.tsx
> fix: make darkmode default to os setting

- packages/nextjs/utils/scaffold-eth/notification.tsx
Solves #286 
Notifications will look like this now:
> feat: notifications now follow the theme

- packages/nextjs/components/Footer.tsx
- packages/nextjs/components/example-ui/ContractInteraction.tsx
- packages/nextjs/components/scaffold-eth/Balance.tsx
- packages/nextjs/components/scaffold-eth/Input/EtherInput.tsx
- packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx
- packages/nextjs/hooks/scaffold-eth/index.ts
- packages/nextjs/hooks/scaffold-eth/useAccountBalance.ts
- packages/nextjs/hooks/scaffold-eth/useNativeCurrencyPrice.ts
- packages/nextjs/pages/_app.tsx
- packages/nextjs/services/store/store.ts
- packages/nextjs/utils/scaffold-eth/fetchPriceFromUniswap.ts
- packages/nextjs/utils/scaffold-eth/networks.ts
> feat: native currency symbol as per target network

- README.md
Update Custom Hooks section on README
Closes [273](https://github.com/scaffold-eth/scaffold-eth-2/issues/273)
> Update readme: custom hooks section

- packages/nextjs/hooks/scaffold-eth/useScaffoldContract.ts
- packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
> fix: assert type as Abi to avoid ts error

- packages/nextjs/package.json
Typo on `node_modules` folder.
> node_modules in format command

- templates/base/packages/nextjs/package.json
Tries to solve https://github.com/scaffold-eth/scaffold-eth-2/pull/413#issuecomment-1634873376 at least for now but we can keep an eye on #419
> CLI/lock viem and wagmi version 

- package.json
Adding the monorepo commands for subgraph package
- [ x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)
NA
Shutterblock.eth
> adding in subgraph package monorepo commands into main package config

- src/types.ts
> Remove unused types

- RFC-extensions.md
- templates/base/packages/nextjs/scaffold.config.ts.template.mjs
- templates/extensions/foundry/packages/nextjs/scaffold.config.ts.args.mjs
- templates/extensions/hardhat/packages/nextjs/scaffold.config.ts.args.mjs
- templates/utils.js
From https://github.com/scaffold-eth/scaffold-eth-2/pull/425, I left [a comment](https://github.com/scaffold-eth/scaffold-eth-2/pull/425#pullrequestreview-1534668142) where I mention an API change for `withDefaults`. This is what it'd take, although I haven't tested it yet.
If we think this makes sense, I'll run some tests to make sure this works as expected and would also update the RFC.
> Update withDefaults API to receive an object

- package.json
- templates/base/packages/nextjs/components/scaffold-eth/Faucet.tsx
- templates/base/packages/nextjs/components/scaffold-eth/FaucetButton.tsx
- templates/base/packages/nextjs/components/scaffold-eth/Input/AddressInput.tsx
- templates/base/packages/nextjs/components/scaffold-eth/Input/Bytes32Input.tsx
- templates/base/packages/nextjs/components/scaffold-eth/Input/BytesInput.tsx
- templates/base/packages/nextjs/components/scaffold-eth/Input/EtherInput.tsx
- templates/base/packages/nextjs/components/scaffold-eth/Input/InputBase.tsx
- templates/base/packages/nextjs/components/scaffold-eth/Input/IntegerInput.tsx
- templates/base/packages/nextjs/components/scaffold-eth/Input/utils.ts
- templates/base/packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx
- templates/base/packages/nextjs/hooks/scaffold-eth/index.ts
- templates/base/packages/nextjs/hooks/scaffold-eth/useAutoConnect.ts
- templates/base/packages/nextjs/services/web3/wagmiConfig.tsx
Merges latest main commit's into CLI and updated the version
> merge main in cli and version++

- .gitmodules
- README.md
- packages/foundry/package.json
- packages/foundry/remappings.txt
- packages/foundry/script/Deploy.s.sol
- packages/foundry/script/DeployHelpers.s.sol
Closes #470 #468 
Your ENS/address: jrcarlos2000.eth
> Foundry Updates

- README.md
We merged #385 PR but forgot to update the README, checkout this comment https://github.com/scaffold-eth/scaffold-eth-2/pull/385#discussion_r1238972572
None
> update example for using writeAsync in README.md

- README.md
I think this is helpful...
Your ENS/address: 0xwildhare.eth
> added "git checkout foundry" to readme

- package.json
I missed these on a previous pull request, adding in abi-copy and codegen to package.json
- [ x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)
None
> adding a couple scripts missing to package.json

- packages/nextjs/components/Footer.tsx
- packages/nextjs/components/Header.tsx
- packages/nextjs/components/blockexplorer/PaginationButton.tsx
- packages/nextjs/components/blockexplorer/SearchBar.tsx
- packages/nextjs/components/blockexplorer/TransactionsTable.tsx
- packages/nextjs/components/example-ui/ContractInteraction.tsx
- packages/nextjs/components/scaffold-eth/Contract/DisplayVariable.tsx
- packages/nextjs/components/scaffold-eth/Contract/ReadOnlyFunctionForm.tsx
- packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx
- packages/nextjs/components/scaffold-eth/Faucet.tsx
- packages/nextjs/components/scaffold-eth/FaucetButton.tsx
- packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx
- packages/nextjs/package.json
- packages/nextjs/pages/blockexplorer/address/[address].tsx
- packages/nextjs/pages/blockexplorer/transaction/[txHash].tsx
- yarn.lock
Migrated to daisy UI to v3 and minor update for tailwindcss 
Lol although the [changelog](https://daisyui.com/docs/changelog/#breaking-changes) was pretty straightforward but there were many internal things which needed to handle like `btn` class now adds `gap-2`  without you mentioning it so had to update elements which had two childs with parent as `btn` and many others small caveats like this in `dropdown` too
Nevertheless I went through all the changes properly so that all the things alighn with `main` branch 🙌
Also solved #366 
Closes #467 , #122 
> Bump daisyui to v3 & update tailwindcss

- packages/hardhat/hardhat.config.ts
- packages/nextjs/package.json
- yarn.lock
Updated Wagmi and Rainbow to the latest version, There have been a lot of internal changes with walletConnect which Wagmi and Rainbowkit doing check out #431, So just making sure we are up-to-date with it 🙌 
I have locked the version of `wagmi` & `rainbowkit` because of #419 and also wagmi suggest that it in their docs : 
> It is highly recommended that you **lock** your `wagmi` package version to a specific patch release and upgrade with the expectation that types may be fixed or upgraded between any release.
-[Wagmi docs](https://wagmi.sh/react/typescript) 
I have also tested and everything works without breaking types / errors 🙌
> update wagmi & rainbow

- package.json
- templates/base/packages/nextjs/components/Footer.tsx
- templates/base/packages/nextjs/components/Header.tsx
- templates/base/packages/nextjs/components/blockexplorer/PaginationButton.tsx
- templates/base/packages/nextjs/components/blockexplorer/SearchBar.tsx
- templates/base/packages/nextjs/components/blockexplorer/TransactionsTable.tsx
- templates/base/packages/nextjs/components/example-ui/ContractInteraction.tsx
- templates/base/packages/nextjs/components/scaffold-eth/Contract/DisplayVariable.tsx
- templates/base/packages/nextjs/components/scaffold-eth/Contract/ReadOnlyFunctionForm.tsx
- templates/base/packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx
- templates/base/packages/nextjs/components/scaffold-eth/Faucet.tsx
- templates/base/packages/nextjs/components/scaffold-eth/FaucetButton.tsx
- templates/base/packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx
- templates/base/packages/nextjs/package.json
- templates/base/packages/nextjs/pages/blockexplorer/address/[address].tsx
- templates/base/packages/nextjs/pages/blockexplorer/transaction/[txHash].tsx
- templates/extensions/foundry/packages/foundry/foundry.toml
- templates/extensions/hardhat/packages/hardhat/hardhat.config.ts
Back merging some library updates which we recently added 🙌 : 
1. #490 
2. #491 
> back merge lib updates

- packages/hardhat/package.json
- yarn.lock
It's been a long since we updated the `hardhat` version, this also solves #539 
tested by deploying contracts locally, [sepolia](https://sepolia.etherscan.io/address/0x1b5b73f9Ad1b680729697605532d5BceaCecF4b8#code), [polygonZkEvmTestnet](https://testnet-zkevm.polygonscan.com/address/0x62dD5D9E715A74e22349345B5c08411D7183600e)
fixes #539 
> update hardhat version

- packages/hardhat/hardhat.config.ts
- packages/nextjs/utils/scaffold-eth/networks.ts
> Add Scroll Sepolia testnet

- .changeset/polite-carrots-smash.md
- contributors/DEVELOPER-GUIDE.md
- templates/base/packages/nextjs/components/Footer.tsx
- templates/base/packages/nextjs/components/scaffold-eth/Input/AddressInput.tsx
- templates/base/packages/nextjs/components/scaffold-eth/Input/utils.ts
- templates/base/packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
- templates/base/packages/nextjs/tailwind.config.js
- Tweak DaisyUI link (#560)
- Improve ENS support (accept all TLDs) (#563)
- fix: memo history events (#565)
- update  DEVELOPER-GUIDE.md with backmerge-main instructions
> backmerge latest main changes to cli

- packages/nextjs/hooks/scaffold-eth/useBurnerWallet.ts
- packages/nextjs/hooks/scaffold-eth/useTransactor.tsx
> Fix typos in comments

- packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
- after `fromBlock` change fetches all events from `fromBlock` and rewrites events state. Independent of `watch` parameter
- changes `isLoading` behavior since `readEvents` function can be called more than once
_Closes #{issue number}_
> fix: polling fromBlock

- .changeset/silver-baboons-confess.md
- templates/base/packages/nextjs/components/scaffold-eth/Input/IntegerInput.tsx
- templates/base/packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
- templates/base/packages/nextjs/utils/scaffold-eth/contract.ts
- Add disableMultiplyBy1e18 flag to IntegerInput component (#609)
- Add pooling interval to EventHistory hook (#597)
- Fix AbiFunctionReturnType removing [0] (#610)
> Weekly CLI backmerge

- README.md
> add pointers about components and hooks in README

- .github/ISSUE_TEMPLATE/bug_report.yml
This will help us get more clarity in first question, since now we have two methods of using SE-2 
Checkout the flow by creating issue on : https://github.com/technophile-04/se-2/issues/new/choose
> add question for installation method in issue template

- packages/nextjs/contracts/externalContracts.ts
Fixing syntax error in the code example for `externalContracts` object.
Closes #652
> Fix externalContracts object example code

- packages/nextjs/utils/scaffold-eth/contractsData.ts
It by mistake went into #647, also tried finding some other unwanted console.logs but others seems good to me
> remove console log from contractsData

- packages/hardhat/hardhat.config.ts
- packages/nextjs/utils/scaffold-eth/networks.ts
Adding support for Astar testnet zKatana, tested
- [x ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)
NA
> add astarZkatana to networks.ts and hardhat config

- README.md
Updated Readme screenshot example to have current block explorer placement.
Closes #704 
Your ENS/address: pabl0cks.eth
> Update Readme screenshot example to change Block explorer placement

- packages/nextjs/app/debug/_components/contract/ContractUI.tsx
It seems that it was the same problem which face at #535 (Rainbowkit wallet was diconnecting), adding `// @refresh reset` fixes it
Thanks to @carletex for debugging :) 
Closes #736
> add refresh reset at ContractUI

- .changeset/wet-carrots-laugh.md
- templates/extensions/foundry/package.json
- templates/extensions/foundry/packages/foundry/package.json
There is catch, you need to pass in path for contract file eg: 
```bash
yarn flatten contracts/YourContract.sol
```
> add foundry flatten script

- package.json
- packages/hardhat/package.json
Adding the yarn flatten command into subgraph-package
NA, discussed on telegram
> adding flatten command

- package.json
- packages/hardhat/package.json
- packages/subgraph/graph-node/matchstick/Dockerfile
- packages/subgraph/package.json
- packages/subgraph/tests/asserts.test.ts
Adding support to run matchstick test on subgraph using `yarn test`
NA
> Subgraph package

- packages/subgraph/README.md
Simple steps showing how to test using matchstick
NA
> readme update for matchstick

- packages/hardhat/contracts/YourContract.sol
I can't believe this has been wrong for so long.  🤣 
NA
> changing the emit of the value to be correct e.g. msg.value and not 0

- templates/base/.vercelignore.template.mjs
- templates/extensions/foundry/.vercelignore.args.mjs
- templates/extensions/hardhat/.vercelignore.args.mjs
Inline with #768, added them as template so that in future any extensions can add the necessary stuff to it
After this we could merge #756
> add .vercelignore template

- packages/nextjs/components/scaffold-eth/Input/InputBase.tsx
_Concise description of proposed changes, We recommend using screenshots and videos for better description_
_Closes #{issue number}_
> chore: fix typo

- .gitignore
- packages/hardhat/.gitignore
- packages/nextjs/.gitignore
Gitignored dist folder and updated gitigore files
> Gitignored dist folder and updated gitigore files

- packages/nextjs/package.json
- yarn.lock
Fixes #841
Example test code : 
```tsx
const { signMessageAsync } = useSignMessage();
<button
className="btn btn-primary"
onClick={async () => {
try {
const x = await signMessageAsync({
message: "hello",
});
console.log("Signature is :", x);
} catch (err) {
console.log(err, "err");
}
}}
>
Sign Message
</button>
```
> bump burner-connector version

- packages/nextjs/types/utils.ts
This has been hiding in the codebase for while :/
> remove unused type Tuple

- packages/nextjs/components/scaffold-eth/FaucetButton.tsx
- packages/nextjs/components/ui/tooltip.tsx
- packages/nextjs/package.json
- yarn.lock
Shadcn faucet button (non styled)
https://github.com/user-attachments/assets/e2d6d3de-9d01-41d2-8f87-19e807ef2e45
> Shadcn faucet button

- packages/nextjs/package.json
- yarn.lock
> Up wagmi and viem

- packages/hardhat/hardhat.config.ts
- packages/nextjs/utils/scaffold-eth/networks.ts
We would like to add Celo as a network to the Scaffold ETH template, before the ETH Global hackathon, but also because we have received a few requests from our community! 
We love this project and our community does at well! thank you for your work! 
_Closes #{#979}_  (currently opened as a discussion item)
Your ENS/address: gigahierz.eth
> Add celo to networks

- packages/nextjs/app/blockexplorer/page.tsx
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "targeNetwork" to "targetNetwork".
Please review the changes and let me know if any additional changes are needed.
> fix: typos in documentation files

- packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
- packages/nextjs/utils/scaffold-eth/contract.ts
See description and steps to reproduce here https://github.com/scaffold-eth/scaffold-eth-2/issues/1013
Fixes https://github.com/scaffold-eth/scaffold-eth-2/issues/1013
> Fix useScaffoldEventHistory duplicated events

- package.json
- packages/nextjs/package.json
Add Vercel login script to allow to login to Vercel.
> Add vercel login script

- packages/nextjs/package.json
- yarn.lock
We recently updated wagmi and viem versions in https://github.com/scaffold-eth/burner-connector/pull/33 and also it now contains https://github.com/scaffold-eth/burner-connector/pull/27
> up burner-connector

- package.json
- packages/hardhat/package.json
- packages/hardhat/scripts/revealPK.ts
> yarn account:reveal-pk

- package.json
- packages/foundry/package.json
- packages/foundry/scripts-js/checkAccountBalance.js
- packages/foundry/scripts-js/listKeystores.js
- packages/foundry/scripts-js/revealPK.js
Foundry version for https://github.com/scaffold-eth/scaffold-eth-2/pull/1091 command. 
To test run: 
```shell
yarn account:reveal-pk
```
> add reveal pk command

- packages/nextjs/package.json
- yarn.lock
Will fix https://github.com/scaffold-eth/create-eth/issues/259 after backmerging to `create-eth` 
(waits for `burner-connector` update)
> Up viem, wagmi and rainbowkit

- packages/nextjs/package.json
- yarn.lock
Fixes #1104 
Created this https://github.com/scaffold-eth/burner-connector/pull/42 to solve type error issue
But updating to latest version seems to cause the indexDB bug error in console :(
> up wagmi, viem and rainbow-me/rainbwkit

- packages/hardhat/.env.example
- packages/hardhat/hardhat.config.ts
- packages/hardhat/package.json
- yarn.lock
hardhat-deploy started supporting v2 api key https://github.com/wighawag/hardhat-deploy/blob/v1/CHANGELOG.md#104 
fixes #1115 
NOTE: We need to change the default etherscan v2 api key from SE-2 before merging it 
EDIT: The default api key seems to work nicely, cc @portdeveloper can you please try deploying to monad testnet and verify with SE-2 default API key?  
1. Add new testnetwork which supports etherscan v2
2. Copy this contract to `YourContract.sol` (no need to change 00_deploy) 
<details>
<summary>
YourContract.sol
</summary>
```solidity 
//SPDX-License-Identifier: MIT
pragma solidity >=0.8.0 <0.9.0;
// Useful for debugging. Remove when deploying to a live network.
import "hardhat/console.sol";
/**
* A social smart contract that allows users to create profiles, share messages, and …
```
> up hardhat-deploy allowing etherscan v2 api for verification 

- packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
- packages/nextjs/utils/scaffold-eth/contract.ts
Changing fromBlock param to optional and using the new deployedOnBlock value from deployedContracts.
If this change is approved, I will create another PR to update the documentation.
To test this new feature, you can replace the code on page.tsx with:
```"use client";
import { useState } from "react";
import Link from "next/link";
import { useAccount } from "wagmi";
import { BugAntIcon, MagnifyingGlassIcon } from "@heroicons/react/24/outline";
import { Address } from "~~/components/scaffold-eth";
import { useScaffoldEventHistory, useScaffoldWriteContract } from "~~/hooks/scaffold-eth";
const { address: connectedAddress } = useAccount();
const [newGreeting, setNewGreeting] = useState("");
const { writeContractAsync: …
```
> Use deployedOnBlock from deployedContracts in useScaffoldEventHistory

- packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/AddressInfoDropdown.tsx
- packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/RevealBurnerPKModal.tsx
- packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/index.tsx
https://github.com/user-attachments/assets/625325eb-e01a-4605-8fdb-c804d3925243
Fixes #1125
> reveal burner pk option

- packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
Fixes this : https://github.com/scaffold-eth/create-eth/actions/runs/16674616228/job/47198269656?pr=328
> fix `fromBlockValue` type or empty contracts

- packages/nextjs/app/debug/_components/contract/ReadOnlyFunctionForm.tsx
- packages/nextjs/app/debug/_components/contract/WriteOnlyFunctionForm.tsx
- packages/nextjs/components/scaffold-eth/Input/AddressInput.tsx
This PR fixes the issue related to refocusing in the AddressInput component. Fix scaffold-eth/scaffold-ui#20
> fix: refocus for AddressInput component on success

- packages/nextjs/scaffold.config.ts
We have correct url in `hardhat.config.ts` but here we missed it. Thanks to Austin for noticing it 🙌
> fix bg rpc url 
